import type { Lang } from '../i18n';

interface L {
  en: string;
  ko: string;
}

export interface AlmanacEntry {
  title: L;
  short: L;
  body: L;
  funFact: L;
  uncertaintyNote?: L;
  cosmicEra: {
    timeRange: L;
    temperature: L;
    keyParticles: L; // joined string
    keyEvents: L;    // joined string
    realWorldScale: L;
  };
}

/** Resolve a localised value, falling back to English if Korean is missing. */
export function pickLang(value: L | undefined, lang: Lang): string {
  if (!value) return '';
  return value[lang] || value.en;
}

export const ALMANAC: Record<number, AlmanacEntry> = {
  1: {
    title: { en: 'Inflation', ko: '인플레이션' },
    short: { en: 'Space balloons outward faster than light can cross it.',
             ko: '공간이 빛이 건너기도 전에 바깥쪽으로 부풀어 오릅니다.' },
    body: { en: 'Right after the Big Bang, space swelled so wildly that tiny quantum ripples were stretched into the seeds of everything that came later. It was a very short moment, but it set the shape of the whole universe.',
            ko: '빅뱅 직후, 공간은 너무나 격렬하게 부풀어 양자 잔물결이 이후 모든 구조의 씨앗으로 늘어났습니다. 아주 짧은 순간이었지만, 우주 전체의 형태를 결정했습니다.' },
    funFact: { en: 'During inflation, the universe may have grown by a factor bigger than 10^26.',
               ko: '인플레이션 동안, 우주는 10^26배 이상 커졌을 수 있습니다.' },
    uncertaintyNote: { en: 'Inflation is theoretical, and estimates for this era span roughly 1e-36 to 1e-32 seconds.',
                       ko: '인플레이션은 이론적이며, 이 시대의 추정치는 대략 1e-36초에서 1e-32초 사이입니다.' },
    cosmicEra: {
      timeRange: { en: 'about 10^-36 s to 10^-32 s', ko: '약 10^-36초에서 10^-32초' },
      temperature: { en: 'near 10^28 K, model-dependent', ko: '약 10^28 K, 모델에 따라 달라짐' },
      keyParticles: { en: 'Inflaton field, Quantum fluctuations, Spacetime', ko: '인플라톤 장, 양자 요동, 시공간' },
      keyEvents: { en: 'Rapid expansion, Quantum ripples stretched, Reheating begins',
                   ko: '급격한 팽창, 양자 잔물결의 확장, 재가열 시작' },
      realWorldScale: { en: 'A tiny patch may have expanded by more than 10^26 in a fraction of a second.',
                        ko: '아주 작은 영역이 찰나에 10^26배 이상 팽창했을 수 있습니다.' },
    },
  },
  2: {
    title: { en: 'Baryogenesis', ko: '바리온 생성' },
    short: { en: 'Matter survives by the smallest possible margin.',
             ko: '물질은 가장 작은 차이로 살아남습니다.' },
    body: { en: 'Matter and antimatter should have canceled each other almost perfectly. For reasons we still do not fully understand, matter won by a tiny sliver. That tiny survival is why stars, planets, and people can exist.',
            ko: '물질과 반물질은 거의 완벽하게 서로를 상쇄했어야 합니다. 아직 완전히 이해되지 않은 이유로 물질이 아주 미세하게 승리했습니다. 그 작은 생존 덕분에 별, 행성, 사람이 존재할 수 있습니다.' },
    funFact: { en: 'If matter and antimatter had balanced perfectly, the universe would be almost pure light.',
               ko: '물질과 반물질이 완벽히 균형을 이뤘다면, 우주는 거의 순수한 빛이었을 것입니다.' },
    cosmicEra: {
      timeRange: { en: 'roughly 10^-32 s to 10^-12 s', ko: '약 10^-32초에서 10^-12초' },
      temperature: { en: 'about 10^27 K down to 10^15 K', ko: '약 10^27 K에서 10^15 K로' },
      keyParticles: { en: 'Quarks, Antiquarks, Leptons, Gauge bosons', ko: '쿼크, 반쿼크, 렙톤, 게이지 보손' },
      keyEvents: { en: 'Matter-antimatter imbalance, CP violation candidates, Baryon number excess',
                   ko: '물질-반물질 불균형, CP 대칭성 깨짐 후보, 바리온 수 과잉' },
      realWorldScale: { en: 'Only about one extra matter particle per billion pairs is enough to make the visible universe.',
                        ko: '10억 쌍당 단 한 개의 추가 물질 입자만으로도 가시 우주를 만들기에 충분합니다.' },
    },
  },
  3: {
    title: { en: 'Quark-Gluon Plasma', ko: '쿼크-글루온 플라스마' },
    short: { en: 'The early cosmos is a particle soup too hot for atoms.',
             ko: '초기 우주는 원자가 형성되기에는 너무 뜨거운 입자 수프입니다.' },
    body: { en: 'At this stage the universe is so hot that quarks cannot stay locked inside protons or neutrons. Everything behaves more like a fluid than a set of stable particles.',
            ko: '이 단계에서 우주는 너무 뜨거워 쿼크가 양성자나 중성자 안에 갇혀 있을 수 없습니다. 모든 것이 안정된 입자라기보다 유체처럼 행동합니다.' },
    funFact: { en: 'Particle colliders can recreate tiny flashes of quark-gluon plasma for an instant.',
               ko: '입자 가속기는 쿼크-글루온 플라스마의 아주 작은 섬광을 순간적으로 재현할 수 있습니다.' },
    cosmicEra: {
      timeRange: { en: 'about 10^-12 s to 10^-6 s', ko: '약 10^-12초에서 10^-6초' },
      temperature: { en: 'around 10^15 K to 10^13 K', ko: '약 10^15 K에서 10^13 K' },
      keyParticles: { en: 'Quarks, Gluons, Leptons, Photons', ko: '쿼크, 글루온, 렙톤, 광자' },
      keyEvents: { en: 'Quark-gluon plasma, Strong-force confinement approaching, Hadronization begins',
                   ko: '쿼크-글루온 플라스마, 강력 가둠 임박, 강입자 형성 시작' },
      realWorldScale: { en: 'CERN heavy-ion collisions briefly recreate droplets of this early-universe plasma.',
                        ko: 'CERN의 중이온 충돌은 초기 우주 플라스마의 작은 방울을 잠시 재현합니다.' },
    },
  },
  4: {
    title: { en: 'Nucleosynthesis', ko: '핵합성' },
    short: { en: 'The first light nuclei lock into place.', ko: '최초의 가벼운 원자핵이 자리를 잡습니다.' },
    body: { en: 'In the first few minutes, protons and neutrons combine into hydrogen, helium, and trace amounts of lithium. This is the first real chemistry of the universe.',
            ko: '처음 몇 분 동안, 양성자와 중성자는 결합하여 수소, 헬륨, 그리고 미량의 리튬을 만듭니다. 이것이 우주 최초의 진정한 화학입니다.' },
    funFact: { en: 'Most of the ordinary matter in your body was chemically prepared by stages like this and later stars.',
               ko: '여러분 몸의 보통 물질 대부분은 이런 단계와 이후의 별들에 의해 화학적으로 준비되었습니다.' },
    cosmicEra: {
      timeRange: { en: 'about 1 s to 20 min', ko: '약 1초에서 20분' },
      temperature: { en: '10^10 K to 10^8 K', ko: '10^10 K에서 10^8 K' },
      keyParticles: { en: 'Protons, Neutrons, Deuterium, Helium-4, Lithium-7',
                      ko: '양성자, 중성자, 중수소, 헬륨-4, 리튬-7' },
      keyEvents: { en: 'Neutron decay, Deuterium bottleneck breaks, Light nuclei form',
                   ko: '중성자 붕괴, 중수소 병목 돌파, 가벼운 핵 형성' },
      realWorldScale: { en: 'The early mix settles near 75 % hydrogen and 25 % helium by mass, with trace lithium.',
                        ko: '초기 혼합은 질량 기준 약 75% 수소와 25% 헬륨, 그리고 미량의 리튬으로 정착합니다.' },
    },
  },
  5: {
    title: { en: 'Recombination', ko: '재결합' },
    short: { en: 'Electrons settle down and the fog lifts.', ko: '전자가 안정되고 안개가 걷힙니다.' },
    body: { en: 'Electrons finally slow enough to bind with nuclei. Once atoms form, light can travel freely, and the universe becomes transparent for the first time.',
            ko: '전자가 마침내 충분히 느려져 핵과 결합합니다. 원자가 형성되자 빛이 자유롭게 이동할 수 있고, 우주는 처음으로 투명해집니다.' },
    funFact: { en: 'The glow from recombination still exists today as the cosmic microwave background.',
               ko: '재결합 시기의 빛은 오늘날에도 우주배경복사로 남아 있습니다.' },
    cosmicEra: {
      timeRange: { en: 'about 380,000 yr', ko: '약 38만 년' },
      temperature: { en: 'about 3000 K', ko: '약 3000 K' },
      keyParticles: { en: 'Electrons, Protons, Hydrogen atoms, CMB photons',
                      ko: '전자, 양성자, 수소 원자, CMB 광자' },
      keyEvents: { en: 'Atoms form, Photons decouple, Cosmic microwave background released',
                   ko: '원자 형성, 광자 분리, 우주배경복사 방출' },
      realWorldScale: { en: 'The CMB is a snapshot from when the universe first became transparent to light.',
                        ko: 'CMB는 우주가 처음으로 빛에 투명해졌을 때의 스냅샷입니다.' },
    },
  },
  6: {
    title: { en: 'Cosmic Dark Age', ko: '우주 암흑시대' },
    short: { en: 'The universe is full of gas but has no stars yet.',
             ko: '우주는 기체로 가득 차 있지만 아직 별은 없습니다.' },
    body: { en: 'After the first light escapes, space becomes dark again. Hydrogen drifts through a quiet universe while gravity slowly deepens tiny differences.',
            ko: '최초의 빛이 풀려난 뒤, 공간은 다시 어두워집니다. 수소는 조용한 우주를 떠돌고, 중력은 미세한 차이를 천천히 깊게 만듭니다.' },
    funFact: { en: 'This dark age lasted far longer than all of recorded human history.',
               ko: '이 암흑시대는 기록된 인류 역사 전체보다 훨씬 더 오래 지속되었습니다.' },
    cosmicEra: {
      timeRange: { en: 'about 380,000 yr to 100-200 Myr', ko: '약 38만 년에서 1억~2억 년' },
      temperature: { en: '3000 K falling toward tens of K', ko: '3000 K에서 수십 K로 하강' },
      keyParticles: { en: 'Neutral hydrogen, Helium, Dark matter halos, CMB photons',
                      ko: '중성 수소, 헬륨, 암흑물질 헤일로, CMB 광자' },
      keyEvents: { en: 'No stars yet, Gas cools, Density ripples grow',
                   ko: '아직 별 없음, 기체 냉각, 밀도 잔물결 성장' },
      realWorldScale: { en: 'The universe is transparent but mostly unlit, waiting for gravity to gather the first stars.',
                        ko: '우주는 투명하지만 거의 빛이 없으며, 중력이 첫 별을 모으기를 기다립니다.' },
    },
  },
  7: {
    title: { en: 'First Stars', ko: '최초의 별' },
    short: { en: 'Hydrogen clouds collapse into the first blazing suns.',
             ko: '수소 구름이 무너져 최초의 타오르는 태양으로 변합니다.' },
    body: { en: 'Gravity pulls huge clouds of hydrogen together until fusion turns on. These first stars are big, hot, and short-lived, but they begin making heavier elements.',
            ko: '중력이 거대한 수소 구름을 끌어모아 핵융합이 점화됩니다. 이 첫 별들은 크고, 뜨겁고, 짧은 수명을 가지지만, 무거운 원소를 만들기 시작합니다.' },
    funFact: { en: 'The first stars likely contained almost no metals at all.',
               ko: '최초의 별들은 금속(중원소)이 거의 전혀 없었을 가능성이 큽니다.' },
    cosmicEra: {
      timeRange: { en: 'about 100-200 Myr', ko: '약 1억~2억 년' },
      temperature: { en: 'gas clouds cool to hundreds of K before collapse',
                     ko: '기체 구름은 붕괴 전 수백 K로 냉각' },
      keyParticles: { en: 'Hydrogen, Helium, Molecular hydrogen, Population III stars',
                      ko: '수소, 헬륨, 분자 수소, 종족 III 별' },
      keyEvents: { en: 'First fusion ignition, UV light appears, First heavy elements seeded',
                   ko: '첫 핵융합 점화, 자외선 출현, 최초의 무거운 원소 씨앗' },
      realWorldScale: { en: 'The first stars likely formed in small dark-matter halos and burned hotter than later stars.',
                        ko: '최초의 별들은 작은 암흑물질 헤일로에서 형성되어 후대 별보다 더 뜨겁게 탔습니다.' },
    },
  },
  8: {
    title: { en: 'Reionization', ko: '재이온화' },
    short: { en: 'Young stars carve clear windows through cosmic gas.',
             ko: '어린 별들이 우주 기체를 뚫고 투명한 창을 새깁니다.' },
    body: { en: 'Ultraviolet light from the first stars and galaxies strips electrons away from neutral hydrogen. The universe becomes easier for light to cross and easier for structure to reveal itself.',
            ko: '최초의 별과 은하에서 나온 자외선이 중성 수소에서 전자를 떼어냅니다. 빛이 가로지르기 더 쉬워지고 구조가 드러나기 시작합니다.' },
    funFact: { en: 'Astronomers still study exactly how patchy and fast reionization was.',
               ko: '천문학자들은 재이온화가 얼마나 듬성듬성하고 빨랐는지 여전히 연구합니다.' },
    uncertaintyNote: { en: 'The end of reionization is usually placed around 0.5 to 1 billion years after the Big Bang, with active debate around the details.',
                       ko: '재이온화의 끝은 보통 빅뱅 후 5억~10억 년으로 추정되며, 세부사항은 활발히 논의됩니다.' },
    cosmicEra: {
      timeRange: { en: 'about 400 Myr to 1 Gyr', ko: '약 4억 년에서 10억 년' },
      temperature: { en: 'intergalactic gas reheated to around 10^4 K',
                     ko: '은하 간 기체가 약 10^4 K로 재가열' },
      keyParticles: { en: 'Ionized hydrogen, Free electrons, UV photons, Young galaxies',
                      ko: '이온화 수소, 자유 전자, 자외선 광자, 어린 은하' },
      keyEvents: { en: 'Ionization bubbles grow, Dark Ages end, Early galaxies become visible',
                   ko: '이온화 거품 성장, 암흑시대 종료, 초기 은하 가시화' },
      realWorldScale: { en: 'Reionization is patchy: bubbles around young stars overlap over hundreds of millions of years.',
                        ko: '재이온화는 듬성듬성합니다. 어린 별 주위의 거품이 수억 년에 걸쳐 겹칩니다.' },
    },
  },
  9: {
    title: { en: 'Galaxy Formation', ko: '은하 형성' },
    short: { en: 'Matter settles into webs, halos, and spirals.',
             ko: '물질이 거미줄, 헤일로, 나선으로 정착합니다.' },
    body: { en: 'Gravity builds large-scale structure from countless small clumps. Filaments stretch across space, galaxies grow in halos, and the cosmic web becomes visible.',
            ko: '중력이 수많은 작은 덩어리에서 거대 구조를 만듭니다. 필라멘트가 공간을 가로질러 뻗어나가고, 은하는 헤일로 안에서 성장하며, 우주 거미줄이 가시화됩니다.' },
    funFact: { en: 'On the largest scales, the universe looks a little like glowing foam or neural tissue.',
               ko: '가장 큰 규모에서 우주는 빛나는 거품이나 신경 조직과 약간 비슷해 보입니다.' },
    cosmicEra: {
      timeRange: { en: 'about 1 Gyr onward', ko: '약 10억 년 이후' },
      temperature: { en: 'galaxy gas spans about 10^4 K to millions K',
                     ko: '은하 기체는 약 10^4 K에서 수백만 K까지' },
      keyParticles: { en: 'Stars, Gas, Dark matter, Black holes', ko: '별, 기체, 암흑물질, 블랙홀' },
      keyEvents: { en: 'Galaxies merge, Cosmic web matures, Quasars and disks grow',
                   ko: '은하 병합, 우주 거미줄 성숙, 퀘이사와 원반 성장' },
      realWorldScale: { en: 'Modern estimates allow hundreds of billions of galaxies in the observable universe.',
                        ko: '현대 추정으로는 관측 가능 우주에 수천억 개의 은하가 있습니다.' },
    },
  },
  10: {
    title: { en: 'Solar System', ko: '태양계 형성' },
    short: { en: 'Dust, rock, and ice negotiate the shapes of worlds.',
             ko: '먼지, 바위, 얼음이 세계의 형태를 협상합니다.' },
    body: { en: 'Around a young star, grains collide, stick, melt, and crash again. Over time, this messy disk sorts itself into planets, moons, asteroids, and leftovers.',
            ko: '어린 별 주위에서 알갱이들이 충돌하고, 들러붙고, 녹고, 다시 부딪힙니다. 시간이 흐르면서 이 어수선한 원반은 행성, 위성, 소행성, 잔해로 정리됩니다.' },
    funFact: { en: 'Earth likely formed through many giant impacts, including one that helped create the Moon.',
               ko: '지구는 달 형성에 기여한 거대 충돌을 포함해 수많은 거대 충돌을 통해 형성되었을 가능성이 큽니다.' },
    cosmicEra: {
      timeRange: { en: 'about 9.2 Gyr after Big Bang; 4.6 Gyr ago locally',
                   ko: '빅뱅 후 약 92억 년, 지역적으로는 46억 년 전' },
      temperature: { en: 'disk dust ranges from icy tens K to rocky thousands K near the Sun',
                     ko: '원반 먼지는 얼음 수십 K부터 태양 근처 바위 수천 K까지' },
      keyParticles: { en: 'Dust grains, Planetesimals, Ices, Silicates, Metals',
                      ko: '먼지 알갱이, 미행성체, 얼음, 규산염, 금속' },
      keyEvents: { en: 'Solar nebula collapses, Protoplanetary disk forms, Planet embryos accrete',
                   ko: '태양 성운 붕괴, 원시 행성 원반 형성, 행성 배아 응집' },
      realWorldScale: { en: 'NASA summarizes Solar System formation as a 4.6-billion-year-old disk of gas and dust becoming worlds.',
                        ko: 'NASA는 태양계 형성을 46억 년 된 가스·먼지 원반이 세계가 된 과정으로 요약합니다.' },
    },
  },
  11: {
    title: { en: 'Life on Earth', ko: '지구의 생명' },
    short: { en: 'Chemistry learns to copy itself and remember.',
             ko: '화학이 스스로를 복제하고 기억하는 법을 배웁니다.' },
    body: { en: 'On one small planet, molecules begin making more of themselves. Evolution then turns simple chemistry into ecosystems, minds, stories, and civilizations.',
            ko: '하나의 작은 행성에서 분자가 스스로를 더 많이 만들기 시작합니다. 진화가 단순한 화학을 생태계, 정신, 이야기, 문명으로 바꿉니다.' },
    funFact: { en: 'For most of Earth’s history, life was microscopic.',
               ko: '지구 역사 대부분 동안 생명은 미시적이었습니다.' },
    cosmicEra: {
      timeRange: { en: 'about 9.8 Gyr after Big Bang to now', ko: '빅뱅 후 약 98억 년부터 현재까지' },
      temperature: { en: 'Earth surface mostly hundreds K', ko: '지구 표면은 대부분 수백 K' },
      keyParticles: { en: 'Water, Carbon compounds, RNA/DNA, Cells, Oxygen',
                      ko: '물, 탄소 화합물, RNA/DNA, 세포, 산소' },
      keyEvents: { en: 'Abiogenesis candidates, Photosynthesis, Multicellularity, Cambrian diversification',
                   ko: '생명 발생 후보, 광합성, 다세포화, 캄브리아 대폭발' },
      realWorldScale: { en: 'Most Earth history is microbial; complex multicellular life is a late chapter.',
                        ko: '지구 역사 대부분은 미생물의 시대이며, 복잡한 다세포 생명은 후기 장에 해당합니다.' },
    },
  },
  12: {
    title: { en: 'Death of Star', ko: '별의 죽음' },
    short: { en: 'A familiar star grows into a red giant and consumes its neighbors.',
             ko: '익숙한 별이 적색거성으로 자라나 이웃을 삼킵니다.' },
    body: { en: 'When a star like the Sun runs low on core hydrogen, it swells enormously. Inner planets lose their safe orbits, and once-stable worlds are swallowed or scorched away.',
            ko: '태양 같은 별이 중심부 수소가 고갈되면 엄청나게 부풀어 오릅니다. 안쪽 행성은 안전한 궤도를 잃고, 한때 안정적이던 세계는 삼켜지거나 그을립니다.' },
    funFact: { en: 'Mercury and Venus are expected to be lost first if the Sun follows the standard script.',
               ko: '태양이 표준 시나리오를 따른다면 수성과 금성이 먼저 사라질 것으로 예상됩니다.' },
    cosmicEra: {
      timeRange: { en: 'about 5 Gyr in Earth’s future', ko: '지구의 약 50억 년 미래' },
      temperature: { en: 'red-giant envelope thousands K; core much hotter',
                     ko: '적색거성 외피는 수천 K, 중심부는 훨씬 더 뜨거움' },
      keyParticles: { en: 'Helium core, Hydrogen shell, Stellar wind, Planetary debris',
                      ko: '헬륨 중심부, 수소 껍질, 항성풍, 행성 잔해' },
      keyEvents: { en: 'Sun leaves main sequence, Red giant expansion, Inner planets engulfed or scorched',
                   ko: '태양 주계열 이탈, 적색거성 팽창, 안쪽 행성 흡수 또는 그을림' },
      realWorldScale: { en: 'NASA notes the Sun may expand to about 100 times its current diameter as a red giant.',
                        ko: 'NASA는 태양이 적색거성으로서 현재 지름의 약 100배까지 팽창할 수 있다고 봅니다.' },
    },
  },
  13: {
    title: { en: 'Stelliferous End', ko: '항성 시대의 끝' },
    short: { en: 'The age of ordinary starlight fades out.', ko: '평범한 별빛의 시대가 사라집니다.' },
    body: { en: 'Star formation slows and then mostly stops. What remains is a universe filled with cooling remnants, dim leftovers, and less fresh light with each passing era.',
            ko: '별 형성이 느려지다 거의 멈춥니다. 남는 것은 식어가는 잔해, 희미한 유물, 그리고 시대가 지날수록 줄어드는 새 빛으로 채워진 우주입니다.' },
    funFact: { en: 'Even after bright stars are gone, the universe can keep changing for absurdly long times.',
               ko: '밝은 별들이 사라진 뒤에도 우주는 터무니없이 긴 시간 동안 계속 변할 수 있습니다.' },
    cosmicEra: {
      timeRange: { en: 'about 10^14 yr', ko: '약 10^14년' },
      temperature: { en: 'stellar remnants cool toward background temperature',
                     ko: '항성 잔해가 배경 온도로 식어감' },
      keyParticles: { en: 'White dwarfs, Neutron stars, Brown dwarfs, Black dwarfs',
                      ko: '백색왜성, 중성자별, 갈색왜성, 흑색왜성' },
      keyEvents: { en: 'Star formation ends, Last red dwarfs fade, Remnants dominate',
                   ko: '별 형성 종료, 마지막 적색왜성 소멸, 잔해 우위' },
      realWorldScale: { en: 'The bright-star era is finite; low-mass stars stretch it far beyond the current age.',
                        ko: '밝은 별의 시대는 유한하며, 저질량 별들은 그것을 현 우주 나이보다 훨씬 더 늘립니다.' },
    },
  },
  14: {
    title: { en: 'Degenerate Era', ko: '축퇴 시대' },
    short: { en: 'Matter itself begins to feel temporary.', ko: '물질 자체가 일시적인 것처럼 느껴지기 시작합니다.' },
    body: { en: 'White dwarfs, neutron stars, and cold leftovers dominate. If proton decay is real, even matter that seems solid and permanent will eventually come apart.',
            ko: '백색왜성, 중성자별, 차가운 잔해가 지배합니다. 양성자 붕괴가 실재한다면, 단단하고 영원해 보이는 물질조차 결국 흩어집니다.' },
    funFact: { en: 'Some versions of physics predict that proton decay is so slow we have never directly seen it.',
               ko: '일부 물리 이론은 양성자 붕괴가 너무 느려 우리가 직접 본 적이 없다고 예측합니다.' },
    uncertaintyNote: { en: 'Proton decay timing depends on GUT models; estimates can range from about 1e34 to 1e45 years.',
                       ko: '양성자 붕괴 시기는 대통일 이론 모델에 따라 다르며, 추정치는 약 1e34년에서 1e45년 사이입니다.' },
    cosmicEra: {
      timeRange: { en: 'about 10^40 yr, model-dependent', ko: '약 10^40년, 모델에 따라 달라짐' },
      temperature: { en: 'near-background; rare decay events dominate',
                     ko: '배경에 가깝고, 드문 붕괴 사건이 지배' },
      keyParticles: { en: 'Protons, Leptons, Photons, Degenerate remnants',
                      ko: '양성자, 렙톤, 광자, 축퇴 잔해' },
      keyEvents: { en: 'Possible proton decay, Remnants dissolve, Matter becomes radiation',
                   ko: '가능한 양성자 붕괴, 잔해 소멸, 물질이 복사로 전환' },
      realWorldScale: { en: 'This era depends on physics not yet observed; proton decay remains an open experimental question.',
                        ko: '이 시대는 아직 관측되지 않은 물리에 의존하며, 양성자 붕괴는 미해결 실험 문제로 남아 있습니다.' },
    },
  },
  15: {
    title: { en: 'Black Hole Era', ko: '블랙홀 시대' },
    short: { en: 'Black holes inherit the future, then slowly evaporate.',
             ko: '블랙홀이 미래를 물려받고, 그 후 천천히 증발합니다.' },
    body: { en: 'After almost everything else has faded, black holes remain as the biggest structures left. Hawking radiation leaks them away over unbelievable stretches of time.',
            ko: '거의 모든 것이 사라진 뒤에도 블랙홀은 남은 가장 큰 구조로 남습니다. 호킹 복사가 믿을 수 없는 시간에 걸쳐 그들을 흩어 보냅니다.' },
    funFact: { en: 'A supermassive black hole can outlive ordinary stars by many, many orders of magnitude.',
               ko: '초대질량 블랙홀은 평범한 별보다 여러 자릿수 더 오래 살아남을 수 있습니다.' },
    uncertaintyNote: { en: 'Evaporation time varies enormously by mass, from around 1e67 years for stellar black holes to about 1e100 years for supermassive ones.',
                       ko: '증발 시간은 질량에 따라 크게 달라지며, 항성 블랙홀은 약 1e67년, 초대질량은 약 1e100년입니다.' },
    cosmicEra: {
      timeRange: { en: 'about 10^67 yr to 10^100 yr and beyond', ko: '약 10^67년에서 10^100년, 그 이상' },
      temperature: { en: 'black holes grow colder with mass; final evaporation heats sharply',
                     ko: '블랙홀은 질량이 클수록 더 차가워지고, 마지막 증발은 급격히 뜨거워짐' },
      keyParticles: { en: 'Black holes, Hawking photons, Gravitons, Leptons',
                      ko: '블랙홀, 호킹 광자, 중력자, 렙톤' },
      keyEvents: { en: 'Black holes dominate, Slow evaporation, Final bursts for small holes',
                   ko: '블랙홀 우위, 느린 증발, 작은 블랙홀의 마지막 폭발' },
      realWorldScale: { en: 'Theoretical Hawking evaporation makes black holes the longest-lived major structures.',
                        ko: '이론적 호킹 증발은 블랙홀을 가장 오래 살아남는 주요 구조로 만듭니다.' },
    },
  },
  16: {
    title: { en: 'The End', ko: '마지막' },
    short: { en: 'The universe reaches the point where endings compete.',
             ko: '우주가 결말들이 경쟁하는 지점에 도달합니다.' },
    body: { en: 'At the far future, the story can branch. The cosmos may coast into equilibrium, collapse inward, tear apart, or be replaced by a deeper vacuum state.',
            ko: '먼 미래에 이야기는 갈라질 수 있습니다. 우주는 평형으로 흘러가거나, 안쪽으로 붕괴하거나, 찢어지거나, 더 깊은 진공 상태로 대체될 수 있습니다.' },
    funFact: { en: 'Different cosmic endings depend on the long-term behavior of expansion, matter, and quantum fields.',
               ko: '서로 다른 우주적 결말은 팽창, 물질, 양자장의 장기적 행동에 달려 있습니다.' },
    uncertaintyNote: { en: 'Heat death is asymptotic, while Big Rip, Big Crunch, vacuum decay, and bounce scenarios remain model-dependent alternatives.',
                       ko: '열적 죽음은 점근적이며, 빅 립, 빅 크런치, 진공 붕괴, 바운스 시나리오는 모델 의존적 대안으로 남습니다.' },
    cosmicEra: {
      timeRange: { en: '10^100 yr to open-ended futures', ko: '10^100년에서 열린 미래까지' },
      temperature: { en: 'approaches the lowest available background temperature',
                     ko: '도달 가능한 가장 낮은 배경 온도에 접근' },
      keyParticles: { en: 'Photons, Leptons, Gravitons, Vacuum fluctuations',
                      ko: '광자, 렙톤, 중력자, 진공 요동' },
      keyEvents: { en: 'Heat death, Possible vacuum decay, Possible rip/crunch/bounce alternatives',
                   ko: '열적 죽음, 가능한 진공 붕괴, 가능한 립/크런치/바운스 대안' },
      realWorldScale: { en: 'The far future is dominated by model choice: expansion history and quantum vacuum stability decide the ending.',
                        ko: '먼 미래는 모델 선택이 지배합니다. 팽창 역사와 양자 진공 안정성이 결말을 결정합니다.' },
    },
  },
};
