import type {
  RogueTypeDefinition,
  RogueTypeKey,
  SingularityUnlockDefinition,
  SingularityUnlockId,
} from './types';

export const STORAGE_KEYS = {
  save: 'cosmic_coalescence_save_v7',
  muted: 'cosmic_coalescence_muted',
} as const;

export const TUNING = {
  COMBO_TIMEOUT_MS: 700,
  COMBO_CLEAR_MS: 1200,
  COMBO_MULT_PER_10: 0.4,
  COMBO_MULT_MAX: 8.0,
  CRIT_BASE_CHANCE: 0.05,
  CRIT_PER_COMBO: 0.01,
  CRIT_MAX: 0.5,
  CRIT_MULT: 5,
  CRIT_MULT_GAIN_PER_LEVEL: 1,

  CAMERA_DAMPENING: 0.985,
  CAMERA_MAX_VELOCITY: 1.8,
  CAMERA_AMBIENT_DRIFT: 0.012,
  CAMERA_DRIFT_ROTATION: 0.00012,
  CLICK_NUDGE_STRENGTH: 0.08,

  FIRST_ENCOUNTER_DELAY_MS: 18000,
  ENCOUNTER_INTERVAL_MIN_MS: 10000,
  ENCOUNTER_INTERVAL_MAX_MS: 25000,
  TRAVEL_DIRECTION_BIAS: 0.7,
  ROGUE_EXPIRE_MS: 35000,
  ROGUE_SPAWN_RADIUS_FRAC: 0.65,
  ROGUE_TARGET_RECT_FRAC: 0.5,
  ROGUE_SPEED_MIN: 0.5,
  ROGUE_SPEED_MAX: 1.0,
  ROGUE_DESPAWN_DISTANCE_FRAC: 1.6,
  ROGUE_INDICATOR_MARGIN: 24,
  ROGUE_INDICATOR_PULSE_MS: 220,

  AMBIENT_PARTICLE_COUNT: 80,
  STAR_LAYERS: [
    { count: 100, depth: 0.15, rMin: 0.4, rMax: 1.0, alphaMin: 0.15, alphaMax: 0.4 },
    { count: 70, depth: 0.4, rMin: 0.6, rMax: 1.4, alphaMin: 0.25, alphaMax: 0.6 },
    { count: 35, depth: 0.8, rMin: 0.8, rMax: 1.8, alphaMin: 0.35, alphaMax: 0.85 },
  ],
  WAKE_TRAIL_MAX: 40,
  BURST_MAX: 200,
  FLYER_MAX: 80,
  SHOCKWAVE_MAX: 8,
  MAX_FLOATING_NUMBERS: 60,
  ROGUE_MAX: 5,
  STAR_WRAP_MARGIN: 5,
  STAR_STREAK_THRESHOLD: 0.4,
  STAR_STREAK_MULTIPLIER: 3,

  MOTE_MAX: 40,
  MOTE_PER_CLICK: 1,
  MOTE_PER_AUTO_TICK: 1,
  MOTE_AUTO_SPAWN_INTERVAL_MS: 250,
  MOTE_NEIGHBOR_K: 3,
  MOTE_NEIGHBOR_REFRESH_MS: 200,
  MOTE_ANCHOR_GRAVITY: 0.8,
  MOTE_PEER_GRAVITY: 0.18,
  MOTE_REPULSION_STRENGTH: 0.1,
  MOTE_REPULSION_DISTANCE: 6,
  MOTE_CLUSTER_MIN_RADIUS: 22,
  MOTE_CLUSTER_MAX_RADIUS: 132,
  MOTE_CLUSTER_GROW_PER_SQRT_MOTE: 4.8,
  MOTE_DAMPENING: 0.965,
  MOTE_MAX_SPEED: 3.2,
  MOTE_MERGE_DISTANCE: 4,
  MOTE_MERGE_MAX_MASS: 12,
  MOTE_BASE_MASS: 1,
  MOTE_BASE_RADIUS: 1.2,
  MOTE_RADIUS_PER_MASS: 0.42,
  MOTE_SPAWN_RADIUS_FRAC: 0.1,

  GALAXY_TANGENTIAL_BOOST: 1.4,
  GALAXY_SPIRAL_ARMS: 2,
  GALAXY_FLAT_BIAS: 0.85,
  GALAXY_DISK_MIN_RADIUS: 46,
  GALAXY_DISK_MAX_RADIUS: 170,
  GALAXY_DISK_GROW_PER_SQRT_MOTE: 8,

  PLANETARY_ORBIT_LOCK: 0.7,
  PLANETARY_ORBIT_MIN_RADIUS: 46,
  PLANETARY_ORBIT_MAX_RADIUS: 160,
  PLANETARY_ORBIT_GROW_PER_SQRT_MOTE: 7.5,

  LIFE_SURFACE_R: 60,
  LIFE_LIGHT_PER_CLICK: 1,
  LIFE_FEATURE_GROW_MS: 800,
  LIFE_EARTH_ROT_RATE: 0.00015,

  BLACKHOLE_DISK_INNER: 38,
  BLACKHOLE_DISK_OUTER_BASE: 52,
  BLACKHOLE_DISK_OUTER_MAX: 165,
  BLACKHOLE_DISK_GROW_PER_MOTE: 0.44,
  BLACKHOLE_DISK_TILT: 0.78,
  BLACKHOLE_PHOTON_RING_R: 44,
  BLACKHOLE_LENS_STRENGTH: 1.6,

  GRAVITY_BASE: 7,
  GRAVITY_PROGRESS_SCALE: 1.8,
  IMPLOSION_GRAVITY: 60,
  PARTICLE_DAMPENING: 0.992,
  PARTICLE_MAX_V: 4.5,
  PARTICLE_CAPTURE_SOFTENING: 35,
  PARTICLE_EDGE_RADIUS_FRAC: 0.55,
  PARTICLE_EDGE_VARIANCE: 80,
  PARTICLE_RESPAWN_MARGIN: 200,

  CLICK_COST_BASE_FRAC: 0.1,
  AUTO_COST_BASE_FRAC: 0.15,
  CRIT_COST_BASE_FRAC: 0.22,
  CLICK_GAIN_PER_LEVEL: 0.5,
  AUTO_GAIN_PER_LEVEL_FRAC: 0.01,
  COST_GROWTH: 1.15,

  CONDENSE_IMPLOSION_MS: 900,
  STAGE_TRANSITION_FADE_MS: 1000,
  STAGE_TRANSITION_SUCK_MS: 260,
  STAGE_TRANSITION_BLAST_MS: 640,
  STAGE_TRANSITION_QUOTE_DELAY_MS: 620,
  STAGE_TRANSITION_TOTAL_MS: 1300,
  STAGE_TRANSITION_REVEAL_MS: 1000,
  STAGE_TRANSITION_BURST_COUNT: 120,
  INTRO_TOTAL_MS: 2200,
  INTRO_DOT_SIZE: 8,
  INTRO_DOT_EXPANDED: 60,
  INTRO_BURST_COUNT: 200,
  INTRO_PULSE_MS: 1200,

  AUTOSAVE_INTERVAL_MS: 30000,
  LOGIC_TICK_MS: 100,
  MAX_OFFLINE_SEC: 28_800,
  OFFLINE_BASE_RATE: 0.5,

  AUDIO_DEFAULT_MUTED: true,
  CLICK_VOLUME_DB: -12,
  DRONE_VOLUME_DB: -28,
  COLLISION_VOLUME_DB: -8,
  BIG_BANG_VOLUME_DB: -10,
  CLICK_MIN_GAP_MS: 10,
  CLICK_RATE_LIMIT_THRESHOLD: 5,
  AUTO_TICK_VOLUME_MULTIPLIER: 0.1,
  AMBIENT_CROSSFADE_MS: 2000,
  TIME_ACCELERATION_WHOOSH_INTERVAL_MS: 1000,

  CORE_BASE_RADIUS: 14,
  CORE_PROGRESS_RADIUS: 70,
  CORE_WHITE_MIN_RADIUS: 4,
  CORE_WHITE_RADIUS_FRAC: 0.18,
  CORE_GLOW_RADIUS_MULT: 2.2,
  FIELD_GLOW_RADIUS_FRAC: 0.5,
  THRESHOLD_RING_RADIUS_MULT: 1.5,
  THRESHOLD_RING_OSCILLATION: 8,
  SHOCKWAVE_SPEED_PX_PER_SEC: 800,
  SHOCKWAVE_FADE_MS: 1500,
  BURST_DECAY: 0.025,
  BURST_VELOCITY_DECAY: 0.93,
  FLYER_CLICK_SPEED: 7,
  FLYER_AUTO_SPEED: 5,
  FLYER_GRAVITY_PULL: 350,
  FLYER_AUTO_LIFE_DECAY: 0.008,
  FLYER_CLICK_LIFE_DECAY: 0.012,
  WAKE_LIFE_DECAY: 0.015,
  WAKE_MIN_SPEED: 0.5,
  WAKE_SPAWN_CHANCE_MULT: 0.35,

  MINOR_COLLISION_BURST_COUNT: 8,
  MAJOR_COLLISION_BURST_COUNT: 16,
  MASSIVE_COLLISION_BURST_COUNT: 30,
  CLICK_BURST_COUNT: 2,
  CRIT_BURST_COUNT: 6,
  SHAKE_SMALL_MS: 550,
  SHAKE_BIG_MS: 700,
  FLOAT_NORMAL_MS: 1000,
  FLOAT_CRIT_MS: 1400,
  FLOAT_COLLISION_MS: 2000,
  ENCOUNTER_ALERT_MS: 1700,

  RESET_MODAL_Z_INDEX: 140,
  QUOTE_Z_INDEX: 120,
  OVERLAY_Z_INDEX: 30,
  MOBILE_MIN_WIDTH: 768,
  BLACK_HOLE_ALPHA_BOOST: 1.5,
  TOTAL_REAL_SECONDS: 360_000,
  ACTIVE_PLAY_FRACTION: 0.3,
  IDLE_PLAY_FRACTION: 0.7,
  MOBILE_MAX_CPS: 10,
} as const;

export const SINGULARITY_UNLOCKS: SingularityUnlockDefinition[] = [
  {
    id: 'quark_foam',
    label: 'Quark Foam',
    cost: 10,
    effect: '+1 click power per level forever',
    description: 'Vacuum texture leaves a permanent residue in every new universe.',
  },
  {
    id: 'free_combo',
    label: 'Free Combo',
    cost: 25,
    effect: 'Combo cap +2.0',
    description: 'Momentum survives the collapse a little longer than it should.',
  },
  {
    id: 'stellar_memory',
    label: 'Stellar Memory',
    cost: 50,
    effect: 'Retain 25% of upgrade levels between stages',
    description: 'Dying structures leave a memory trace in what follows them.',
  },
  {
    id: 'hawking_echo',
    label: 'Hawking Echo',
    cost: 100,
    effect: 'Offline progress at full rate',
    description: 'Even unattended universes continue to whisper into the void.',
  },
  {
    id: 'inflaton_spark',
    label: 'Inflaton Spark',
    cost: 200,
    effect: 'Skip Inflation on prestige',
    description: 'The opening expansion no longer needs to be relearned from silence.',
  },
  {
    id: 'cosmic_web',
    label: 'Cosmic Web',
    cost: 400,
    effect: 'Encounter rewards doubled, spawn rate increased',
    description: 'Large-scale structure bends wanderers back toward the center.',
  },
  {
    id: 'red_shift',
    label: 'Red Shift',
    cost: 800,
    effect: 'Late stages compress faster',
    description: 'The remote future begins to lean harder into visible motion.',
  },
  {
    id: 'multiverse_lens',
    label: 'Multiverse Lens',
    cost: 2000,
    effect: 'Seed customization reserved',
    description: 'You begin to see neighboring histories through the grain.',
  },
  {
    id: 'vacuum_stability',
    label: 'Vacuum Stability',
    cost: 8000,
    effect: 'Unlock Vacuum Decay',
    description: 'A deeper floor reveals itself beneath apparent emptiness.',
  },
  {
    id: 'boltzmann_brain',
    label: 'Boltzmann Brain',
    cost: 30000,
    effect: 'Heat death continues indefinitely',
    description: 'Equilibrium stops pretending to be the end of narration.',
  },
];

export const SINGULARITY_UNLOCK_LOOKUP: Record<SingularityUnlockId, SingularityUnlockDefinition> =
  Object.fromEntries(SINGULARITY_UNLOCKS.map((unlock) => [unlock.id, unlock])) as Record<
    SingularityUnlockId,
    SingularityUnlockDefinition
  >;

export const ROGUE_TYPES: Record<RogueTypeKey, RogueTypeDefinition> = {
  minor: {
    weight: 60,
    r: 8,
    bonusMultiplier: 0.4,
    entropyBonus: 10,
    color: '#88ddff',
    glowColor: '#aaeeff',
    name: 'Wandering Quantum',
  },
  major: {
    weight: 32,
    r: 18,
    bonusMultiplier: 1.8,
    entropyBonus: 50,
    color: '#ffcc66',
    glowColor: '#ffee99',
    name: 'Stellar Fragment',
  },
  massive: {
    weight: 8,
    r: 36,
    bonusMultiplier: 6,
    entropyBonus: 200,
    color: '#ff7755',
    glowColor: '#ffaa88',
    name: 'Rogue Mass',
  },
};
