export const STAGE_PARTICLES: Record<number, string[]> = {
  1: ['Spacetime', 'Vacuum', 'Quantum Foam', 'Inflaton'],
  2: ['Quark', 'Antiquark', 'Gluon', 'Lepton', 'Photon'],
  3: ['Up Quark', 'Down Quark', 'Strange Quark', 'Gluon', 'Photon', 'Neutrino'],
  4: ['Proton', 'Neutron', 'Hydrogen-1', 'Helium-4', 'Lithium-7', 'Deuterium'],
  5: ['Electron', 'Photon (CMB)', 'Hydrogen', 'Helium'],
  6: ['Hydrogen', 'Dark Matter', 'Cold Dust'],
  7: ['H₂', 'Pop III Star', 'Stellar Wind', 'Carbon', 'Oxygen', 'Iron'],
  8: ['UV Photon', 'Ionized H', 'Quasar Beam'],
  9: ['Galaxy', 'Halo', 'Filament', 'Quasar'],
  10: ['Asteroid', 'Dust', 'Planetesimal', 'Moon', 'Earth', 'Mars'],
  11: ['Water', 'RNA', 'Cell', 'Multicellular', 'Mammal', 'Civilization'],
  12: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'],
  13: ['White Dwarf', 'Neutron Star', 'Iron Star'],
  14: ['Decaying Proton', 'Iron Atom', 'Quantum Tunnel'],
  15: ['Hawking Quantum', 'Photon Pair', 'Information'],
  16: ['Vacuum Fluctuation', 'Boltzmann Brain', 'Final Photon'],
};

type SolarPhase =
  | 'pre_stellar'
  | 't_tauri'
  | 'planetesimals'
  | 'inner_planets'
  | 'outer_planets'
  | 'late_bombardment'
  | 'stable'
  | 'first_water'
  | 'civ_preview';

const STAGE_10_PHASE_POOLS: Record<SolarPhase, string[]> = {
  pre_stellar: ['Dust', 'Gas', 'Hydrogen'],
  t_tauri: ['Photon', 'Solar Wind'],
  planetesimals: ['Planetesimal', 'Asteroid', 'Rock'],
  inner_planets: ['Mercury', 'Venus', 'Earth', 'Mars'],
  outer_planets: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
  late_bombardment: ['Meteor', 'Comet', 'Lava'],
  stable: ['Orbit', 'Asteroid Belt', 'Pluto'],
  first_water: ['Water', 'Atmosphere', 'Ocean'],
  civ_preview: ['City Light', 'Civilization', 'Smoke'],
};

function getSolarPhase(progress01: number): SolarPhase {
  if (progress01 < 0.1) return 'pre_stellar';
  if (progress01 < 0.25) return 't_tauri';
  if (progress01 < 0.4) return 'planetesimals';
  if (progress01 < 0.55) return 'inner_planets';
  if (progress01 < 0.7) return 'outer_planets';
  if (progress01 < 0.8) return 'late_bombardment';
  if (progress01 < 0.9) return 'stable';
  if (progress01 < 0.95) return 'first_water';
  return 'civ_preview';
}

export const PARTICLE_DEFINITIONS: Record<string, string> = {
  Spacetime: 'The fabric that lets distance and time exist at all.',
  Vacuum: 'Not empty nothingness, but a restless quantum field.',
  'Quantum Foam': 'Tiny fluctuations in the earliest universe.',
  Inflaton: 'The hypothetical field that drove cosmic inflation.',
  Quark: 'A fundamental particle that helps build protons and neutrons.',
  Antiquark: 'The antimatter partner of a quark.',
  Gluon: 'The force carrier that binds quarks together.',
  Lepton: 'A lightweight particle family that includes the electron.',
  Photon: 'A particle of light.',
  'Up Quark': 'One of the light quarks found inside protons.',
  'Down Quark': 'A light quark that teams up with up quarks in matter.',
  'Strange Quark': 'A heavier quark common in extreme energies.',
  Neutrino: 'A ghostly particle that barely interacts with matter.',
  Proton: 'A positively charged particle in atomic nuclei.',
  Neutron: 'A neutral particle in atomic nuclei.',
  'Hydrogen-1': 'Ordinary hydrogen, the universe’s most common atom.',
  'Helium-4': 'A major relic of the Big Bang, common across the cosmos.',
  'Lithium-7': 'A rare light element formed in early nucleosynthesis.',
  Deuterium: 'Heavy hydrogen with one proton and one neutron.',
  Electron: 'The particle that orbits atomic nuclei.',
  'Photon (CMB)': 'Ancient light released when the universe first became transparent.',
  Hydrogen: 'The simplest and most abundant element in the universe.',
  Helium: 'The second-most common element, forged early.',
  'Dark Matter': 'Invisible mass inferred from its gravitational pull.',
  'Cold Dust': 'Fine material drifting through the dark ages of space.',
  'H₂': 'A hydrogen molecule, the cold fuel of star birth.',
  'Pop III Star': 'One of the first stars, massive and short-lived.',
  'Stellar Wind': 'Fast streams of particles blown from a star.',
  Carbon: 'A heavy element forged inside stars.',
  Oxygen: 'A life-friendly element created in stellar cores.',
  Iron: 'A heavy stellar ash that marks the end of easy fusion.',
  'UV Photon': 'Energetic light that can ionize hydrogen.',
  'Ionized H': 'Hydrogen stripped of its electron.',
  'Quasar Beam': 'Radiation from matter falling into a supermassive black hole.',
  Galaxy: 'A vast system of stars, gas, dust, and dark matter.',
  Halo: 'A galaxy’s extended dark-matter envelope.',
  Filament: 'A thread in the large-scale cosmic web.',
  Quasar: 'An intensely bright galactic core powered by a black hole.',
  Asteroid: 'A rocky body orbiting a star.',
  Dust: 'Fine solid grains that help build planets.',
  Planetesimal: 'A young building block of planets.',
  Moon: 'A natural satellite orbiting a planet.',
  Earth: 'A rocky world with liquid water and life.',
  Mars: 'A cold, dusty world beyond Earth.',
  Water: 'A molecule essential to life as we know it.',
  RNA: 'A molecule that can store information and catalyze reactions.',
  Cell: 'The basic structural unit of life.',
  Multicellular: 'Life made of many cooperating cells.',
  Mammal: 'A warm-blooded vertebrate with hair and milk.',
  Civilization: 'Organized intelligent life shaping a world.',
  Mercury: 'The innermost planet of the solar system.',
  Venus: 'A hot, cloud-wrapped neighbor of Earth.',
  Jupiter: 'The largest planet in the solar system.',
  Saturn: 'A gas giant famous for its rings.',
  Uranus: 'An ice giant tilted on its side.',
  Neptune: 'A deep blue ice giant in the outer solar system.',
  Pluto: 'A distant dwarf world once counted as a planet.',
  'White Dwarf': 'A dense stellar remnant left after a Sun-like star dies.',
  'Neutron Star': 'A collapsed stellar core of extreme density.',
  'Iron Star': 'A far-future remnant imagined after immense cooling.',
  'Decaying Proton': 'A proton imagined to vanish in the deep future.',
  'Iron Atom': 'Matter lingering in the degenerate era.',
  'Quantum Tunnel': 'A probability-driven leap through a barrier.',
  'Hawking Quantum': 'Radiation emitted by an evaporating black hole.',
  'Photon Pair': 'Two linked photons emerging from energetic processes.',
  Information: 'The trace of order carried through physical change.',
  'Vacuum Fluctuation': 'A fleeting quantum event in seemingly empty space.',
  'Boltzmann Brain': 'A hypothetical mind arising from random fluctuation.',
  'Final Photon': 'A last whisper of light in a dying cosmos.',
  Gas: 'Diffuse material in the young solar nebula.',
  'Solar Wind': 'Charged particles streaming from a young star.',
  Rock: 'Solid material gathering into larger bodies.',
  Meteor: 'A bright incoming fragment crossing a planet’s sky.',
  Comet: 'An icy body carrying volatile material through orbit.',
  Lava: 'Molten rock exposed by heavy impacts.',
  Orbit: 'A stable path around a central mass.',
  'Asteroid Belt': 'A ring of leftover rocky bodies between Mars and Jupiter.',
  Atmosphere: 'A layer of gas held around a world by gravity.',
  Ocean: 'A broad body of liquid water on a planetary surface.',
  'City Light': 'A tiny artificial glow on the night side of a world.',
  Smoke: 'A fragile sign of chemistry, fire, and activity.',
};

const PARTICLE_LABELS_KO: Record<string, string> = {
  Spacetime: '시공간',
  Vacuum: '진공',
  'Quantum Foam': '양자 거품',
  Inflaton: '인플라톤',
  Quark: '쿼크',
  Antiquark: '반쿼크',
  Gluon: '글루온',
  Lepton: '렙톤',
  Photon: '광자',
  'Up Quark': '업 쿼크',
  'Down Quark': '다운 쿼크',
  'Strange Quark': '스트레인지 쿼크',
  Neutrino: '중성미자',
  Proton: '양성자',
  Neutron: '중성자',
  'Hydrogen-1': '수소-1',
  'Helium-4': '헬륨-4',
  'Lithium-7': '리튬-7',
  Deuterium: '중수소',
  Electron: '전자',
  'Photon (CMB)': 'CMB 광자',
  Hydrogen: '수소',
  Helium: '헬륨',
  'Dark Matter': '암흑 물질',
  'Cold Dust': '차가운 먼지',
  'H₂': '수소 분자',
  'Pop III Star': '제3종족 별',
  'Stellar Wind': '항성풍',
  Carbon: '탄소',
  Oxygen: '산소',
  Iron: '철',
  'UV Photon': '자외선 광자',
  'Ionized H': '이온화 수소',
  'Quasar Beam': '퀘이사 빔',
  Galaxy: '은하',
  Halo: '헤일로',
  Filament: '필라멘트',
  Quasar: '퀘이사',
  Asteroid: '소행성',
  Dust: '먼지',
  Planetesimal: '미행성체',
  Moon: '달',
  Earth: '지구',
  Mars: '화성',
  Water: '물',
  RNA: 'RNA',
  Cell: '세포',
  Multicellular: '다세포 생명',
  Mammal: '포유류',
  Civilization: '문명',
  Mercury: '수성',
  Venus: '금성',
  Jupiter: '목성',
  Saturn: '토성',
  Uranus: '천왕성',
  Neptune: '해왕성',
  Pluto: '명왕성',
  'White Dwarf': '백색왜성',
  'Neutron Star': '중성자별',
  'Iron Star': '철별',
  'Decaying Proton': '붕괴하는 양성자',
  'Iron Atom': '철 원자',
  'Quantum Tunnel': '양자 터널',
  'Hawking Quantum': '호킹 양자',
  'Photon Pair': '광자 쌍',
  Information: '정보',
  'Vacuum Fluctuation': '진공 요동',
  'Boltzmann Brain': '볼츠만 뇌',
  'Final Photon': '마지막 광자',
  Gas: '가스',
  'Solar Wind': '태양풍',
  Rock: '암석',
  Meteor: '유성',
  Comet: '혜성',
  Lava: '용암',
  Orbit: '궤도',
  'Asteroid Belt': '소행성대',
  Atmosphere: '대기',
  Ocean: '바다',
  'City Light': '도시 불빛',
  Smoke: '연기',
};

const PARTICLE_DEFINITIONS_KO: Record<string, string> = {
  Spacetime: '거리와 시간이 존재하게 하는 우주의 바탕입니다.',
  Vacuum: '완전히 빈 공간이 아니라 요동치는 양자장입니다.',
  'Quantum Foam': '초기 우주의 아주 작은 양자 요동입니다.',
  Inflaton: '우주 인플레이션을 일으켰다고 여겨지는 가상의 장입니다.',
  Quark: '양성자와 중성자를 이루는 기본 입자입니다.',
  Antiquark: '쿼크의 반물질 짝입니다.',
  Gluon: '쿼크를 묶어 주는 힘의 매개 입자입니다.',
  Lepton: '전자를 포함하는 가벼운 입자 계열입니다.',
  Photon: '빛을 이루는 입자입니다.',
  'Up Quark': '양성자 안에서 발견되는 가벼운 쿼크입니다.',
  'Down Quark': '업 쿼크와 함께 물질을 이루는 가벼운 쿼크입니다.',
  'Strange Quark': '극한 에너지에서 자주 나타나는 더 무거운 쿼크입니다.',
  Neutrino: '물질과 거의 상호작용하지 않는 유령 같은 입자입니다.',
  Proton: '원자핵 안의 양전하 입자입니다.',
  Neutron: '원자핵 안의 전하가 없는 입자입니다.',
  'Hydrogen-1': '우주에서 가장 흔한 보통 수소입니다.',
  'Helium-4': '빅뱅의 흔적으로 우주에 널리 남은 헬륨입니다.',
  'Lithium-7': '초기 핵합성에서 생긴 드문 가벼운 원소입니다.',
  Deuterium: '양성자 하나와 중성자 하나를 가진 무거운 수소입니다.',
  Electron: '원자핵 주위를 도는 입자입니다.',
  'Photon (CMB)': '우주가 처음 투명해졌을 때 풀려난 오래된 빛입니다.',
  Hydrogen: '우주에서 가장 단순하고 풍부한 원소입니다.',
  Helium: '초기에 만들어진 두 번째로 흔한 원소입니다.',
  'Dark Matter': '중력 효과로 존재를 추정하는 보이지 않는 물질입니다.',
  'Cold Dust': '우주 암흑시대를 떠도는 차가운 미세 물질입니다.',
  'H₂': '별 탄생의 차가운 연료가 되는 수소 분자입니다.',
  'Pop III Star': '우주 최초 세대의 무겁고 짧게 사는 별입니다.',
  'Stellar Wind': '별에서 불어 나오는 빠른 입자 흐름입니다.',
  Carbon: '별 내부에서 만들어지는 무거운 원소입니다.',
  Oxygen: '별의 핵에서 만들어지는 생명 친화적 원소입니다.',
  Iron: '쉬운 핵융합의 끝을 알리는 무거운 별의 재입니다.',
  'UV Photon': '수소를 이온화할 수 있는 고에너지 빛입니다.',
  'Ionized H': '전자를 잃은 수소입니다.',
  'Quasar Beam': '초대질량 블랙홀로 떨어지는 물질이 내는 강한 복사입니다.',
  Galaxy: '별, 가스, 먼지, 암흑 물질이 모인 거대한 구조입니다.',
  Halo: '은하를 둘러싼 넓은 암흑 물질 외피입니다.',
  Filament: '거대 우주망을 이루는 실 같은 구조입니다.',
  Quasar: '블랙홀이 동력을 공급하는 매우 밝은 은하 중심입니다.',
  Asteroid: '별 주위를 도는 암석 천체입니다.',
  Dust: '행성을 빚는 데 쓰이는 미세한 고체 입자입니다.',
  Planetesimal: '행성의 어린 구성 블록입니다.',
  Moon: '행성 주위를 도는 자연 위성입니다.',
  Earth: '액체 물과 생명을 가진 암석 행성입니다.',
  Mars: '지구 바깥의 차갑고 먼지 많은 행성입니다.',
  Water: '생명에 필수적인 분자입니다.',
  RNA: '정보를 저장하고 반응을 도울 수 있는 분자입니다.',
  Cell: '생명의 기본 구조 단위입니다.',
  Multicellular: '여러 세포가 협력해 이루는 생명입니다.',
  Mammal: '털과 젖을 가진 온혈 척추동물입니다.',
  Civilization: '세계를 바꾸는 조직화된 지적 생명입니다.',
  Mercury: '태양계에서 태양에 가장 가까운 행성입니다.',
  Venus: '뜨겁고 구름에 싸인 지구의 이웃 행성입니다.',
  Jupiter: '태양계에서 가장 큰 행성입니다.',
  Saturn: '고리로 유명한 가스 거성입니다.',
  Uranus: '옆으로 기울어진 얼음 거성입니다.',
  Neptune: '태양계 바깥의 깊고 푸른 얼음 거성입니다.',
  Pluto: '한때 행성으로 분류되던 먼 왜행성입니다.',
  'White Dwarf': '태양 같은 별이 죽은 뒤 남는 조밀한 잔해입니다.',
  'Neutron Star': '극도로 조밀하게 붕괴한 별의 핵입니다.',
  'Iron Star': '아득한 미래의 냉각 뒤 상상되는 잔해입니다.',
  'Decaying Proton': '깊은 미래에 사라질 수 있다고 상상되는 양성자입니다.',
  'Iron Atom': '축퇴 시대에 남아 있는 물질입니다.',
  'Quantum Tunnel': '장벽을 확률적으로 통과하는 양자 도약입니다.',
  'Hawking Quantum': '증발하는 블랙홀이 방출하는 복사입니다.',
  'Photon Pair': '고에너지 과정에서 함께 생겨나는 두 광자입니다.',
  Information: '물리적 변화 속에서도 남는 질서의 흔적입니다.',
  'Vacuum Fluctuation': '비어 보이는 공간에서 잠깐 생기는 양자 사건입니다.',
  'Boltzmann Brain': '무작위 요동에서 생겨난다고 가정되는 마음입니다.',
  'Final Photon': '식어 가는 우주의 마지막 빛 한 줄기입니다.',
  Gas: '젊은 태양 성운의 퍼진 물질입니다.',
  'Solar Wind': '어린 태양에서 흘러나오는 하전 입자입니다.',
  Rock: '더 큰 천체로 모여드는 고체 물질입니다.',
  Meteor: '행성의 하늘을 가로지르는 밝은 파편입니다.',
  Comet: '휘발성 물질을 품고 궤도를 도는 얼음 천체입니다.',
  Lava: '강한 충돌로 드러난 녹은 암석입니다.',
  Orbit: '중심 질량 주위를 도는 안정된 길입니다.',
  'Asteroid Belt': '화성과 목성 사이에 남은 암석 천체의 고리입니다.',
  Atmosphere: '중력에 붙잡힌 행성의 기체층입니다.',
  Ocean: '행성 표면의 넓은 액체 물입니다.',
  'City Light': '밤면에서 보이는 작은 인공 빛입니다.',
  Smoke: '화학, 불, 활동의 연약한 흔적입니다.',
};

export function getParticleNameLabel(name: string, lang: 'en' | 'ko'): string {
  return lang === 'ko' ? PARTICLE_LABELS_KO[name] ?? name : name;
}

export function getParticleDefinitionLabel(name: string, lang: 'en' | 'ko'): string | undefined {
  return lang === 'ko' ? PARTICLE_DEFINITIONS_KO[name] : PARTICLE_DEFINITIONS[name];
}

export function pickParticleName(stageId: number, progress01 = 0): string {
  const pool =
    stageId === 10
      ? STAGE_10_PHASE_POOLS[getSolarPhase(progress01)]
      : STAGE_PARTICLES[stageId] ?? STAGE_PARTICLES[1];
  return pool[Math.floor(Math.random() * pool.length)] ?? 'Particle';
}

const ENTROPY_WEIGHT_GROUPS: Array<{ names: string[]; weight: number }> = [
  {
    weight: 1,
    names: [
      'Vacuum',
      'Photon',
      'Gluon',
      'Lepton',
      'Neutrino',
      'Dust',
      'Gas',
      'Rock',
      'Orbit',
    ],
  },
  {
    weight: 2,
    names: [
      'Spacetime',
      'Quantum Foam',
      'Inflaton',
      'Quark',
      'Antiquark',
      'Up Quark',
      'Down Quark',
      'Strange Quark',
      'Electron',
      'UV Photon',
      'Photon (CMB)',
      'Hawking Quantum',
      'Photon Pair',
      'Final Photon',
      'Vacuum Fluctuation',
    ],
  },
  {
    weight: 3,
    names: [
      'Proton',
      'Neutron',
      'Hydrogen-1',
      'Helium-4',
      'Lithium-7',
      'Deuterium',
      'Hydrogen',
      'Helium',
      'H₂',
      'Ionized H',
      'Carbon',
      'Oxygen',
      'Iron',
      'Iron Atom',
      'Decaying Proton',
      'Quantum Tunnel',
    ],
  },
  {
    weight: 5,
    names: [
      'Dark Matter',
      'Cold Dust',
      'Stellar Wind',
      'Quasar Beam',
      'Halo',
      'Filament',
      'Solar Wind',
      'Meteor',
      'Comet',
      'Lava',
      'Atmosphere',
      'Ocean',
    ],
  },
  {
    weight: 8,
    names: [
      'Pop III Star',
      'Galaxy',
      'Quasar',
      'Asteroid',
      'Planetesimal',
      'Moon',
      'Mercury',
      'Venus',
      'Earth',
      'Mars',
      'Jupiter',
      'Saturn',
      'Uranus',
      'Neptune',
      'Pluto',
      'Asteroid Belt',
      'White Dwarf',
      'Neutron Star',
      'Iron Star',
      'Information',
    ],
  },
  {
    weight: 13,
    names: [
      'Water',
      'RNA',
      'Cell',
      'Multicellular',
      'Mammal',
      'Civilization',
      'City Light',
      'Smoke',
      'Boltzmann Brain',
    ],
  },
];

export function getParticleEntropyBonus(stageId: number, particleName: string, isCrit = false): number {
  const group = ENTROPY_WEIGHT_GROUPS.find((entry) => entry.names.includes(particleName));
  const particleWeight = group?.weight ?? 1;
  const stageIdx = Math.max(0, stageId - 1);
  const stageWeight = Math.pow(1.5, stageIdx);
  const critWeight = isCrit ? 2 : 1;
  return Math.ceil(particleWeight * stageWeight * critWeight);
}
