import type { Stage, StageBackground } from './types';

const COSMIC_YEAR_SECONDS = 31_557_600;

const STAGE_DEFINITIONS: Omit<Stage, 'timelinePos' | 'cosmicTimeSpanSec' | 'background' | 'zoomDirection'>[] = [
  {
    id: 1,
    name: 'Inflation',
    resource: 'Expansion',
    time: '1e-32 s',
    cosmicTimeSec: 1e-32,
    realPlayTargetSec: 30,
    threshold: 1_725,
  clusterMode: 'inflation',
    mechanic: 'click_basic',
    accent: '#ff6b3d',
    coreColor: '#ffb27d',
    particleColors: ['#ff6b3d', '#ffb27d', '#ffe7c2'],
    clickUpgradeName: 'Expansion Pulse',
    autoUpgradeName: 'Vacuum Surge',
    quote:
      'The universe is the ultimate free lunch.',
    quoteAttr: 'Alan Guth',
    quoteKo:
      '우주는 궁극의 공짜 점심이다.',
    quoteAttrKo: '앨런 거스',
  },
  {
    id: 2,
    name: 'Baryogenesis',
    resource: 'Asymmetry',
    time: '1e-12 s',
    cosmicTimeSec: 1e-12,
    realPlayTargetSec: 120,
    threshold: 28_000,
  clusterMode: 'baryogenesis',
    mechanic: 'matter_asymmetry',
    accent: '#ff8a47',
    coreColor: '#ffd08c',
    particleColors: ['#ff8a47', '#ffcf70', '#fff0c9'],
    clickUpgradeName: 'Charge Bias',
    autoUpgradeName: 'Survivor Cascade',
    quote:
      'The cosmos is all that is or ever was or ever will be.',
    quoteAttr: 'Carl Sagan, Cosmos (1980)',
    quoteKo:
      '코스모스는 지금 있는 모든 것이며, 과거에 있었던 모든 것이며, 앞으로 있을 모든 것이다.',
    quoteAttrKo: '칼 세이건, 《코스모스》 (1980)',
  },
  {
    id: 3,
    name: 'Quark-Gluon Plasma',
    resource: 'Quarks',
    time: '1e-6 s',
    cosmicTimeSec: 1e-6,
    realPlayTargetSec: 300,
    threshold: 390_000,
  clusterMode: 'qgPlasma',
    mechanic: 'click_basic',
    accent: '#ff6a45',
    coreColor: '#ffaf74',
    particleColors: ['#ff4a2f', '#ffa523', '#ffe9bf'],
    clickUpgradeName: 'Gluon Bond',
    autoUpgradeName: 'Plasma Pump',
    quote:
      'Nature uses only the longest threads to weave her patterns, so each small piece of her fabric reveals the organization of the entire tapestry.',
    quoteAttr: 'Richard Feynman, The Character of Physical Law (1965)',
    quoteKo:
      '자연은 오직 가장 긴 실만으로 그 패턴을 짜므로, 천의 아주 작은 조각 하나하나가 전체 구조를 드러낸다.',
    quoteAttrKo: '리처드 파인만, 《물리 법칙의 특성》 (1965)',
  },
  {
    id: 4,
    name: 'Nucleosynthesis',
    resource: 'Nuclei',
    time: '3 min',
    cosmicTimeSec: 180,
    realPlayTargetSec: 360,
    threshold: 5_500_000,
  clusterMode: 'nucleosynthesis',
    mechanic: 'fusion_window',
    accent: '#ffb45a',
    coreColor: '#ffe090',
    particleColors: ['#ff9c2f', '#ffd05b', '#fff0ba'],
    clickUpgradeName: 'Fusion Pulse',
    autoUpgradeName: 'Helium Forge',
    quote:
      'Hydrogen is a light, odorless gas which, given enough time, turns into people.',
    quoteAttr: 'Fred Hoyle',
    quoteKo:
      '수소는 가볍고 무색무취의 기체인데, 충분한 시간이 주어지면 사람이 된다.',
    quoteAttrKo: '프레드 호일',
  },
  {
    id: 5,
    name: 'Recombination',
    resource: 'Atoms',
    time: '215 Kyr',
    cosmicTimeSec: 6.8e12,
    realPlayTargetSec: 540,
    threshold: 8e7,
  clusterMode: 'recombination',
    mechanic: 'recombination',
    accent: '#63b7ff',
    coreColor: '#a8dcff',
    particleColors: ['#2f7bc1', '#67c0ff', '#d9f2ff'],
    clickUpgradeName: 'Electron Capture',
    autoUpgradeName: 'Photon Release',
    quote:
      'The more the universe seems comprehensible, the more it also seems pointless.',
    quoteAttr: 'Steven Weinberg, The First Three Minutes (1977)',
    quoteKo:
      '우주가 이해 가능해 보일수록, 더욱 무의미해 보인다.',
    quoteAttrKo: '스티븐 와인버그, 《최초의 3분》 (1977)',
  },
  {
    id: 6,
    name: 'Cosmic Dark Age',
    resource: 'Hydrogen',
    time: '100 Myr',
    cosmicTimeSec: 3.15e15,
    realPlayTargetSec: 1_800,
    threshold: 1.2e9,
  clusterMode: 'darkAge',
    mechanic: 'dark_age',
    accent: '#4e6188',
    coreColor: '#7d90b5',
    particleColors: ['#182237', '#3d4f73', '#92a4c8'],
    clickUpgradeName: 'Cold Drift',
    autoUpgradeName: 'Silent Accretion',
    quote:
      'We have peered into a new world and have seen that it is more mysterious and more complex than we had imagined.',
    quoteAttr: 'Vera Rubin',
    quoteKo:
      '우리는 새로운 세계를 들여다보았으며, 그것이 상상했던 것보다 훨씬 신비롭고 복잡하다는 것을 알았다.',
    quoteAttrKo: '베라 루빈',
    silenceBeforeMs: 5000,
  },
  {
    id: 7,
    name: 'First Stars',
    resource: 'Stars',
    time: '200 Myr',
    cosmicTimeSec: 6.3e15,
    realPlayTargetSec: 3_600,
    threshold: 1.8e10,
  clusterMode: 'firstStars',
    mechanic: 'first_stars',
    accent: '#eef3ff',
    coreColor: '#fffef8',
    particleColors: ['#d6ddff', '#fffef2', '#ffd9a5'],
    clickUpgradeName: 'Protostar Spark',
    autoUpgradeName: 'Population Igniter',
    quote:
      'The nitrogen in our DNA, the calcium in our teeth, the iron in our blood were made in the interiors of collapsing stars. We are made of star-stuff.',
    quoteAttr: 'Carl Sagan, Cosmos (1980)',
    quoteKo:
      '우리 DNA의 질소, 이빨의 칼슘, 피의 철분은 붕괴하는 별의 내부에서 만들어졌다. 우리는 별의 재료다.',
    quoteAttrKo: '칼 세이건, 《코스모스》 (1980)',
  },
  {
    id: 8,
    name: 'Reionization',
    resource: 'Photons',
    time: '500 Myr',
    cosmicTimeSec: 1.6e16,
    realPlayTargetSec: 5_400,
    threshold: 2.8e11,
  clusterMode: 'reionization',
    mechanic: 'reionization',
    accent: '#9bd9ff',
    coreColor: '#dff5ff',
    particleColors: ['#4aa7de', '#8ed8ff', '#ecfbff'],
    clickUpgradeName: 'Ionizing Front',
    autoUpgradeName: 'Luminous Sweep',
    quote:
      'With increasing distance, our knowledge fades. Eventually, we reach the dim boundary — the utmost limits of our telescopes.',
    quoteAttr: 'Edwin Hubble, The Realm of the Nebulae (1936)',
    quoteKo:
      '거리가 멀어질수록 우리의 지식은 사라진다. 결국 우리는 망원경의 최외곽 한계, 어스름한 경계에 다다른다.',
    quoteAttrKo: '에드윈 허블, 《성운의 왕국》 (1936)',
  },
  {
    id: 9,
    name: 'Galaxy Formation',
    resource: 'Galaxies',
    time: '1 Gyr',
    cosmicTimeSec: 3.15e16,
    realPlayTargetSec: 7_200,
    threshold: 4.5e12,
    clusterMode: 'galaxy',
    mechanic: 'galaxy_weaving',
    accent: '#6d8fff',
    coreColor: '#aab8ff',
    particleColors: ['#3548b6', '#6d8fff', '#d9ddff'],
    clickUpgradeName: 'Quasar Beam',
    autoUpgradeName: 'Web Spinner',
    quote:
      'If you\'re religious, it\'s like looking at God.',
    quoteAttr: 'George Smoot, on the COBE CMB data (1992)',
    quoteKo:
      '종교적인 사람이라면, 이것은 신을 보는 것과 같다.',
    quoteAttrKo: '조지 스무트, COBE 우주배경복사 관측 결과에 대해 (1992)',
  },
  {
    id: 10,
    name: 'Solar System',
    resource: 'Worlds',
    time: '9.2 Gyr',
    cosmicTimeSec: 2.9e17,
    realPlayTargetSec: 10_800,
    threshold: 7.5e13,
    clusterMode: 'planetary',
    mechanic: 'planet_formation',
    accent: '#f7c86e',
    coreColor: '#ffe3a8',
    particleColors: ['#b77a35', '#f7c86e', '#fff0d1'],
    clickUpgradeName: 'Planetesimal Pull',
    autoUpgradeName: 'Accretion Disk',
    quote:
      'Look again at that dot. That\'s here. That\'s home. That\'s us.',
    quoteAttr: 'Carl Sagan, Pale Blue Dot (1994)',
    quoteKo:
      '저 점을 다시 보라. 저기가 여기다. 저기가 집이다. 저기가 우리다.',
    quoteAttrKo: '칼 세이건, 《창백한 푸른 점》 (1994)',
  },
  {
    id: 11,
    name: 'Life on Earth',
    resource: 'Memory',
    time: '13.8 Gyr',
    cosmicTimeSec: 4.35e17,
    realPlayTargetSec: 14_400,
    threshold: 1.3e15,
    clusterMode: 'lifeSurface',
    mechanic: 'life_evolution',
    accent: '#68d8a4',
    coreColor: '#a9f0d0',
    particleColors: ['#245f45', '#68d8a4', '#d7ffec'],
    clickUpgradeName: 'Living Spark',
    autoUpgradeName: 'Evolutionary Pressure',
    quote:
      'There is grandeur in this view of life... from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.',
    quoteAttr: 'Charles Darwin, On the Origin of Species (1859)',
    quoteKo:
      '이 생명의 관점에는 위엄이 있다... 이처럼 단순한 시작으로부터 가장 아름답고 경이로운 무한한 형태들이 진화해 왔으며, 지금도 진화하고 있다.',
    quoteAttrKo: '찰스 다윈, 《종의 기원》 (1859)',
  },
  {
    id: 12,
    name: 'Death of Star',
    resource: 'Embers',
    time: '+5 Gyr',
    cosmicTimeSec: 5.83e17,
    realPlayTargetSec: 21_600,
    threshold: 2.4e16,
    clusterMode: 'redGiant',
    mechanic: 'red_giant',
    accent: '#ff633f',
    coreColor: '#ff9e71',
    particleColors: ['#ad2d1f', '#ff633f', '#ffd0ac'],
    clickUpgradeName: 'Last Light',
    autoUpgradeName: 'Red Giant Wind',
    quote:
      'Things fall apart; the centre cannot hold.',
    quoteAttr: 'W.B. Yeats, The Second Coming (1919)',
    quoteKo:
      '모든 것이 흩어진다; 중심은 버틸 수 없다.',
    quoteAttrKo: 'W.B. 예이츠, 《재림》 (1919)',
  },
  {
    id: 13,
    name: 'Stelliferous End',
    resource: 'Remnants',
    time: '1e14 yr',
    cosmicTimeSec: 3.15e21,
    realPlayTargetSec: 36_000,
    threshold: 4.5e17,
  clusterMode: 'remnant',
    mechanic: 'remnant_cooling',
    accent: '#8a90a8',
    coreColor: '#bec3d8',
    particleColors: ['#2a3044', '#7e88a5', '#d9deef'],
    clickUpgradeName: 'White Dwarf Cooler',
    autoUpgradeName: 'Iron Star Compression',
    quote:
      'No matter how far we go into the future, there will always be new things happening, new information coming in, new worlds to explore.',
    quoteAttr: 'Freeman Dyson, Infinite in All Directions (1988)',
    quoteKo:
      '미래가 아무리 멀어도, 항상 새로운 일이 일어나고, 새로운 정보가 오고, 탐험할 새로운 세계가 있을 것이다.',
    quoteAttrKo: '프리먼 다이슨, 《모든 방향으로의 무한》 (1988)',
  },
  {
    id: 14,
    name: 'Degenerate Era',
    resource: 'Decays',
    time: '7e26 yr',
    cosmicTimeSec: 2.29e34,
    realPlayTargetSec: 54_000,
    threshold: 8.5e18,
  clusterMode: 'degenerate',
    mechanic: 'proton_decay',
    accent: '#8e69c9',
    coreColor: '#bf9af0',
    particleColors: ['#26133b', '#7c54b9', '#d8befd'],
    clickUpgradeName: 'Decay Catalyst',
    autoUpgradeName: 'Quantum Tunneling Loop',
    quote:
      'Science cannot solve the ultimate mystery of nature. And that is because, in the last analysis, we ourselves are a part of the mystery that we are trying to solve.',
    quoteAttr: 'Max Planck, Where Is Science Going? (1932)',
    quoteKo:
      '과학은 자연의 궁극적인 신비를 풀 수 없다. 결국 우리 자신이 우리가 풀려는 신비의 일부이기 때문이다.',
    quoteAttrKo: '막스 플랑크, 《과학은 어디로 가는가?》 (1932)',
  },
  {
    id: 15,
    name: 'Black Hole Era',
    resource: 'Hawking Quanta',
    time: '1e28 yr',
    cosmicTimeSec: 3.89e35,
    realPlayTargetSec: 86_400,
    threshold: 1.7e20,
    clusterMode: 'blackHole',
    mechanic: 'hawking_radiation',
    accent: '#5b4671',
    coreColor: '#857299',
    particleColors: ['#12091b', '#352446', '#7d6a91'],
    clickUpgradeName: 'Hawking Radiator',
    autoUpgradeName: 'Event Horizon Drain',
    quote:
      'Not only does God play dice, but he sometimes throws them where they cannot be seen.',
    quoteAttr: 'Stephen Hawking',
    quoteKo:
      '신은 주사위를 던질 뿐 아니라, 때로는 볼 수 없는 곳으로 던진다.',
    quoteAttrKo: '스티븐 호킹',
  },
  {
    id: 16,
    name: 'The End',
    resource: 'Outcomes',
    time: '2e30 yr',
    cosmicTimeSec: 5.01e37,
    realPlayTargetSec: 117_450,
    threshold: 3.5e21,
    clusterMode: 'heatDeath',
    mechanic: 'ending_choice',
    accent: '#70758a',
    coreColor: '#b0b5c7',
    particleColors: ['#050608', '#3c4050', '#8b92a8'],
    clickUpgradeName: 'Vacuum Flicker',
    autoUpgradeName: 'Final Divergence',
    quote:
      'This is the way the world ends / Not with a bang but a whimper.',
    quoteAttr: 'T.S. Eliot, The Hollow Men (1925)',
    quoteKo:
      '세상은 이렇게 끝난다 / 쾅 소리가 아니라 흐느낌으로.',
    quoteAttrKo: 'T.S. 엘리엇, 《텅 빈 사람들》 (1925)',
    silenceBeforeMs: 7000,
  },
];

function getTimelinePos(cosmicTimeSec: number, minLog: number, maxLog: number): number {
  const logValue = Math.log10(cosmicTimeSec);
  if (maxLog === minLog) {
    return 0;
  }
  return ((logValue - minLog) / (maxLog - minLog)) * 100;
}

const cosmicLogs = STAGE_DEFINITIONS.map((stage) => Math.log10(stage.cosmicTimeSec));
const minLog = Math.min(...cosmicLogs);
const maxLog = Math.max(...cosmicLogs);

const ZOOM_DIRECTION_BY_STAGE: Record<number, Stage['zoomDirection']> = {
  1: 'none',
  2: 'out',
  3: 'out',
  4: 'out',
  5: 'out',
  6: 'out',
  7: 'out',
  8: 'out',
  9: 'out',
  10: 'in',
  11: 'in',
  12: 'out',
  13: 'out',
  14: 'out',
  15: 'in',
  16: 'out',
};

const BACKGROUNDS_BY_STAGE: Record<number, StageBackground> = {
  1: {
    gradientTop: '#2b0803',
    gradientBottom: '#050102',
    nebulaIntensity: 0.42,
    starDensity: 0,
    starColor: '#fff3dd',
    distantElementColor: '#ff6b3d',
    distantElements: 'expansion_burst',
  },
  2: {
    gradientTop: '#2d1004',
    gradientBottom: '#050102',
    nebulaIntensity: 0.36,
    starDensity: 0.08,
    starColor: '#ffe2b5',
    distantElementColor: '#ff8a47',
    distantElements: 'pair_streaks',
  },
  3: {
    gradientTop: '#33100a',
    gradientBottom: '#060103',
    nebulaIntensity: 0.48,
    starDensity: 0.05,
    starColor: '#fff2c9',
    distantElementColor: '#ff6a45',
    distantElements: 'plasma_swirl',
  },
  4: {
    gradientTop: '#3b2106',
    gradientBottom: '#060302',
    nebulaIntensity: 0.34,
    starDensity: 0.18,
    starColor: '#fff0ba',
    distantElementColor: '#ffb45a',
    distantElements: 'void',
  },
  5: {
    gradientTop: '#08203a',
    gradientBottom: '#02070d',
    nebulaIntensity: 0.28,
    starDensity: 0.42,
    starColor: '#d9f2ff',
    distantElementColor: '#63b7ff',
    distantElements: 'clearing_fog',
  },
  6: {
    gradientTop: '#060912',
    gradientBottom: '#010207',
    nebulaIntensity: 0.08,
    starDensity: 0.22,
    starColor: '#92a4c8',
    distantElementColor: '#4e6188',
    distantElements: 'void',
  },
  7: {
    gradientTop: '#0d1426',
    gradientBottom: '#02030a',
    nebulaIntensity: 0.16,
    starDensity: 0.76,
    starColor: '#eef3ff',
    distantElementColor: '#eef3ff',
    distantElements: 'bright_pinpoints',
  },
  8: {
    gradientTop: '#08263b',
    gradientBottom: '#020713',
    nebulaIntensity: 0.24,
    starDensity: 0.68,
    starColor: '#ecfbff',
    distantElementColor: '#9bd9ff',
    distantElements: 'ionization_bubbles',
  },
  9: {
    gradientTop: '#0a1233',
    gradientBottom: '#02030d',
    nebulaIntensity: 0.3,
    starDensity: 0.86,
    starColor: '#d9ddff',
    distantElementColor: '#6d8fff',
    distantElements: 'galaxy_field',
  },
  10: {
    gradientTop: '#14110a',
    gradientBottom: '#030304',
    nebulaIntensity: 0.18,
    starDensity: 0.72,
    starColor: '#fff0d1',
    distantElementColor: '#f7c86e',
    distantElements: 'nearby_stars',
  },
  11: {
    gradientTop: '#071a14',
    gradientBottom: '#010403',
    nebulaIntensity: 0.16,
    starDensity: 0.64,
    starColor: '#d7ffec',
    distantElementColor: '#68d8a4',
    distantElements: 'earth_orbit',
  },
  12: {
    gradientTop: '#2a0804',
    gradientBottom: '#050101',
    nebulaIntensity: 0.36,
    starDensity: 0.48,
    starColor: '#ffd0ac',
    distantElementColor: '#ff633f',
    distantElements: 'red_shroud',
  },
  13: {
    gradientTop: '#0d1018',
    gradientBottom: '#020207',
    nebulaIntensity: 0.1,
    starDensity: 0.34,
    starColor: '#d9deef',
    distantElementColor: '#8a90a8',
    distantElements: 'fading_stars',
  },
  14: {
    gradientTop: '#13091f',
    gradientBottom: '#020104',
    nebulaIntensity: 0.08,
    starDensity: 0.24,
    starColor: '#d8befd',
    distantElementColor: '#8e69c9',
    distantElements: 'dim_specks',
  },
  15: {
    gradientTop: '#09040f',
    gradientBottom: '#000000',
    nebulaIntensity: 0.14,
    starDensity: 0.38,
    starColor: '#cbb9dd',
    distantElementColor: '#857299',
    distantElements: 'lensed_field',
  },
  16: {
    gradientTop: '#06070a',
    gradientBottom: '#000000',
    nebulaIntensity: 0.04,
    starDensity: 0.16,
    starColor: '#8b92a8',
    distantElementColor: '#70758a',
    distantElements: 'redshifted_void',
  },
};

export const STAGES: Stage[] = STAGE_DEFINITIONS.map((stage, index, stages) => {
  const previousCosmicTime = index === 0 ? 0 : stages[index - 1].cosmicTimeSec;

  return {
    ...stage,
    background: BACKGROUNDS_BY_STAGE[stage.id],
    cosmicTimeSpanSec: stage.cosmicTimeSec - previousCosmicTime,
    timelinePos: getTimelinePos(stage.cosmicTimeSec, minLog, maxLog),
    zoomDirection: ZOOM_DIRECTION_BY_STAGE[stage.id],
  };
});

export const COSMIC_TIME_UNITS = {
  yearSeconds: COSMIC_YEAR_SECONDS,
} as const;
