import type { Stage } from './types';

const COSMIC_YEAR_SECONDS = 31_557_600;

const STAGE_DEFINITIONS: Omit<Stage, 'timelinePos' | 'cosmicTimeSpanSec'>[] = [
  {
    id: 1,
    name: 'Inflation',
    resource: 'Expansion',
    time: '1e-32 s',
    cosmicTimeSec: 1e-32,
    realPlayTargetSec: 60,
    threshold: 50,
  clusterMode: 'inflation',
    mechanic: 'click_basic',
    accent: '#ff6b3d',
    coreColor: '#ffb27d',
    particleColors: ['#ff6b3d', '#ffb27d', '#ffe7c2'],
    clickUpgradeName: 'Expansion Pulse',
    autoUpgradeName: 'Vacuum Surge',
    quote:
      'Space outruns its own horizon. In less than an instant, the possible becomes unimaginably large.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 2,
    name: 'Baryogenesis',
    resource: 'Asymmetry',
    time: '1e-12 s',
    cosmicTimeSec: 1e-12,
    realPlayTargetSec: 120,
    threshold: 400,
  clusterMode: 'baryogenesis',
    mechanic: 'matter_asymmetry',
    accent: '#ff8a47',
    coreColor: '#ffd08c',
    particleColors: ['#ff8a47', '#ffcf70', '#fff0c9'],
    clickUpgradeName: 'Charge Bias',
    autoUpgradeName: 'Survivor Cascade',
    quote:
      'Matter does not win by much. One survivor in a billion is enough to build every future star and hand.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 3,
    name: 'Quark-Gluon Plasma',
    resource: 'Quarks',
    time: '1e-6 s',
    cosmicTimeSec: 1e-6,
    realPlayTargetSec: 240,
    threshold: 2_400,
  clusterMode: 'qgPlasma',
    mechanic: 'click_basic',
    accent: '#ff6a45',
    coreColor: '#ffaf74',
    particleColors: ['#ff4a2f', '#ffa523', '#ffe9bf'],
    clickUpgradeName: 'Gluon Bond',
    autoUpgradeName: 'Plasma Pump',
    quote:
      'The young universe is still too hot for permanence. Matter exists as a storm before it learns to settle.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 4,
    name: 'Nucleosynthesis',
    resource: 'Nuclei',
    time: '3 min',
    cosmicTimeSec: 180,
    realPlayTargetSec: 360,
    threshold: 12_000,
  clusterMode: 'nucleosynthesis',
    mechanic: 'fusion_window',
    accent: '#ffb45a',
    coreColor: '#ffe090',
    particleColors: ['#ff9c2f', '#ffd05b', '#fff0ba'],
    clickUpgradeName: 'Fusion Pulse',
    autoUpgradeName: 'Helium Forge',
    quote:
      'The furnace cools just enough for the first simple nuclei to hold. A narrow window decides the chemical future.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 5,
    name: 'Recombination',
    resource: 'Atoms',
    time: '380 Kyr',
    cosmicTimeSec: 1.2e13,
    realPlayTargetSec: 540,
    threshold: 80_000,
  clusterMode: 'recombination',
    mechanic: 'recombination',
    accent: '#63b7ff',
    coreColor: '#a8dcff',
    particleColors: ['#2f7bc1', '#67c0ff', '#d9f2ff'],
    clickUpgradeName: 'Electron Capture',
    autoUpgradeName: 'Photon Release',
    quote:
      'The fog thins. Electrons find their homes, and light finally moves freely through a transparent cosmos.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 6,
    name: 'Cosmic Dark Age',
    resource: 'Hydrogen',
    time: '100 Myr',
    cosmicTimeSec: 3.15e15,
    realPlayTargetSec: 1_800,
    threshold: 600_000,
  clusterMode: 'darkAge',
    mechanic: 'dark_age',
    accent: '#4e6188',
    coreColor: '#7d90b5',
    particleColors: ['#182237', '#3d4f73', '#92a4c8'],
    clickUpgradeName: 'Cold Drift',
    autoUpgradeName: 'Silent Accretion',
    quote:
      'No stars yet, no sunrise anywhere. Only neutral hydrogen drifting through a darkness that seems endless.',
    quoteAttr: 'Original cosmic prose',
    silenceBeforeMs: 5000,
  },
  {
    id: 7,
    name: 'First Stars',
    resource: 'Stars',
    time: '200 Myr',
    cosmicTimeSec: 6.3e15,
    realPlayTargetSec: 3_600,
    threshold: 5_000_000,
  clusterMode: 'firstStars',
    mechanic: 'first_stars',
    accent: '#eef3ff',
    coreColor: '#fffef8',
    particleColors: ['#d6ddff', '#fffef2', '#ffd9a5'],
    clickUpgradeName: 'Protostar Spark',
    autoUpgradeName: 'Population Igniter',
    quote:
      'The first stars arrive in blinding blue-white bursts. They live fast, die young, and rewrite the dark.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 8,
    name: 'Reionization',
    resource: 'Photons',
    time: '500 Myr',
    cosmicTimeSec: 1.6e16,
    realPlayTargetSec: 5_400,
    threshold: 50_000_000,
  clusterMode: 'reionization',
    mechanic: 'reionization',
    accent: '#9bd9ff',
    coreColor: '#dff5ff',
    particleColors: ['#4aa7de', '#8ed8ff', '#ecfbff'],
    clickUpgradeName: 'Ionizing Front',
    autoUpgradeName: 'Luminous Sweep',
    quote:
      'Starlight pushes back the neutral haze. The universe becomes legible one ionized frontier at a time.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 9,
    name: 'Galaxy Formation',
    resource: 'Galaxies',
    time: '1 Gyr',
    cosmicTimeSec: 3.15e16,
    realPlayTargetSec: 7_200,
    threshold: 500_000_000,
    clusterMode: 'galaxy',
    mechanic: 'galaxy_weaving',
    accent: '#6d8fff',
    coreColor: '#aab8ff',
    particleColors: ['#3548b6', '#6d8fff', '#d9ddff'],
    clickUpgradeName: 'Quasar Beam',
    autoUpgradeName: 'Web Spinner',
    quote:
      'Gravity gathers light into structure. Filaments, knots, and spirals reveal the hidden architecture of space.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 10,
    name: 'Solar System',
    resource: 'Worlds',
    time: '9.2 Gyr',
    cosmicTimeSec: 2.9e17,
    realPlayTargetSec: 10_800,
    threshold: 5_000_000_000,
    clusterMode: 'planetary',
    mechanic: 'planet_formation',
    accent: '#f7c86e',
    coreColor: '#ffe3a8',
    particleColors: ['#b77a35', '#f7c86e', '#fff0d1'],
    clickUpgradeName: 'Planetesimal Pull',
    autoUpgradeName: 'Accretion Disk',
    quote:
      'Around an ordinary star, dust keeps its appointments. Stone, metal, and ice negotiate the shapes of worlds.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 11,
    name: 'Life on Earth',
    resource: 'Memory',
    time: '13.8 Gyr',
    cosmicTimeSec: 4.35e17,
    realPlayTargetSec: 14_400,
    threshold: 50_000_000_000,
    clusterMode: 'lifeSurface',
    mechanic: 'life_evolution',
    accent: '#68d8a4',
    coreColor: '#a9f0d0',
    particleColors: ['#245f45', '#68d8a4', '#d7ffec'],
    clickUpgradeName: 'Living Spark',
    autoUpgradeName: 'Evolutionary Pressure',
    quote:
      'On one small rock, chemistry learns to remember itself. Almost everything you call history waits inside the final flicker.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 12,
    name: 'Death of Star',
    resource: 'Embers',
    time: '+5 Gyr',
    cosmicTimeSec: 5.83e17,
    realPlayTargetSec: 21_600,
    threshold: 500_000_000_000,
    clusterMode: 'redGiant',
    mechanic: 'red_giant',
    accent: '#ff633f',
    coreColor: '#ff9e71',
    particleColors: ['#ad2d1f', '#ff633f', '#ffd0ac'],
    clickUpgradeName: 'Last Light',
    autoUpgradeName: 'Red Giant Wind',
    quote:
      'The star swells without ceremony. What it consumes is precious only to those who once lived there.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 13,
    name: 'Stelliferous End',
    resource: 'Remnants',
    time: '1e14 yr',
    cosmicTimeSec: 3.15e21,
    realPlayTargetSec: 36_000,
    threshold: 5e12,
  clusterMode: 'remnant',
    mechanic: 'remnant_cooling',
    accent: '#8a90a8',
    coreColor: '#bec3d8',
    particleColors: ['#2a3044', '#7e88a5', '#d9deef'],
    clickUpgradeName: 'White Dwarf Cooler',
    autoUpgradeName: 'Iron Star Compression',
    quote:
      'The era of ordinary starlight ends. The universe keeps going, but the age of lamps is over.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 14,
    name: 'Degenerate Era',
    resource: 'Decays',
    time: '1e40 yr',
    cosmicTimeSec: 3.15e47,
    realPlayTargetSec: 54_000,
    threshold: 5e14,
  clusterMode: 'degenerate',
    mechanic: 'proton_decay',
    accent: '#8e69c9',
    coreColor: '#bf9af0',
    particleColors: ['#26133b', '#7c54b9', '#d8befd'],
    clickUpgradeName: 'Decay Catalyst',
    autoUpgradeName: 'Quantum Tunneling Loop',
    quote:
      'Even the most stubborn matter has an ending. Given enough time, solidity becomes a rumor.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 15,
    name: 'Black Hole Era',
    resource: 'Hawking Quanta',
    time: '1e100 yr',
    cosmicTimeSec: 3.15e107,
    realPlayTargetSec: 86_400,
    threshold: 5e17,
    clusterMode: 'blackHole',
    mechanic: 'hawking_radiation',
    accent: '#5b4671',
    coreColor: '#857299',
    particleColors: ['#12091b', '#352446', '#7d6a91'],
    clickUpgradeName: 'Hawking Radiator',
    autoUpgradeName: 'Event Horizon Drain',
    quote:
      'Black holes inherit the silence. They rule an empty kingdom with a patience measured in impossible years.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 16,
    name: 'The End',
    resource: 'Outcomes',
    time: '1e103 yr',
    cosmicTimeSec: 3.15e110,
    realPlayTargetSec: 117_480,
    threshold: 5e21,
    clusterMode: 'heatDeath',
    mechanic: 'ending_choice',
    accent: '#70758a',
    coreColor: '#b0b5c7',
    particleColors: ['#050608', '#3c4050', '#8b92a8'],
    clickUpgradeName: 'Vacuum Flicker',
    autoUpgradeName: 'Final Divergence',
    quote:
      'Everything approaches equilibrium. And still, at the far edge of silence, one last possibility trembles.',
    quoteAttr: 'Original cosmic prose',
    silenceBeforeMs: 7000,
  },
];

function getTimelinePos(cosmicTimeSec: number, minLog: number, maxLog: number): number {
  const logValue = Math.log10(cosmicTimeSec);
  if (maxLog === minLog) {
    return 0;
  }
  return ((logValue - minLog) / (maxLog - minLog)) * 100;
}

const cosmicLogs = STAGE_DEFINITIONS.map((stage) => Math.log10(stage.cosmicTimeSec));
const minLog = Math.min(...cosmicLogs);
const maxLog = Math.max(...cosmicLogs);

export const STAGES: Stage[] = STAGE_DEFINITIONS.map((stage, index, stages) => {
  const previousCosmicTime = index === 0 ? 0 : stages[index - 1].cosmicTimeSec;

  return {
    ...stage,
    cosmicTimeSpanSec: stage.cosmicTimeSec - previousCosmicTime,
    timelinePos: getTimelinePos(stage.cosmicTimeSec, minLog, maxLog),
  };
});

export const COSMIC_TIME_UNITS = {
  yearSeconds: COSMIC_YEAR_SECONDS,
} as const;
