import type { Stage, StageBackground } from './types';

const COSMIC_YEAR_SECONDS = 31_557_600;

const STAGE_DEFINITIONS: Omit<Stage, 'timelinePos' | 'cosmicTimeSpanSec' | 'background' | 'zoomDirection'>[] = [
  {
    id: 1,
    name: 'Inflation',
    resource: 'Expansion',
    time: '1e-32 s',
    cosmicTimeSec: 1e-32,
    realPlayTargetSec: 30,
    threshold: 1_725,
  clusterMode: 'inflation',
    mechanic: 'click_basic',
    accent: '#ff6b3d',
    coreColor: '#ffb27d',
    particleColors: ['#ff6b3d', '#ffb27d', '#ffe7c2'],
    clickUpgradeName: 'Expansion Pulse',
    autoUpgradeName: 'Vacuum Surge',
    quote:
      'Space outruns its own horizon. In less than an instant, the possible becomes unimaginably large.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 2,
    name: 'Baryogenesis',
    resource: 'Asymmetry',
    time: '1e-12 s',
    cosmicTimeSec: 1e-12,
    realPlayTargetSec: 120,
    threshold: 9.386e8,
  clusterMode: 'baryogenesis',
    mechanic: 'matter_asymmetry',
    accent: '#ff8a47',
    coreColor: '#ffd08c',
    particleColors: ['#ff8a47', '#ffcf70', '#fff0c9'],
    clickUpgradeName: 'Charge Bias',
    autoUpgradeName: 'Survivor Cascade',
    quote:
      'Matter does not win by much. One survivor in a billion is enough to build every future star and hand.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 3,
    name: 'Quark-Gluon Plasma',
    resource: 'Quarks',
    time: '1e-6 s',
    cosmicTimeSec: 1e-6,
    realPlayTargetSec: 300,
    threshold: 1.427e9,
  clusterMode: 'qgPlasma',
    mechanic: 'click_basic',
    accent: '#ff6a45',
    coreColor: '#ffaf74',
    particleColors: ['#ff4a2f', '#ffa523', '#ffe9bf'],
    clickUpgradeName: 'Gluon Bond',
    autoUpgradeName: 'Plasma Pump',
    quote:
      'The young universe is still too hot for permanence. Matter exists as a storm before it learns to settle.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 4,
    name: 'Nucleosynthesis',
    resource: 'Nuclei',
    time: '3 min',
    cosmicTimeSec: 180,
    realPlayTargetSec: 360,
    threshold: 1.211e10,
  clusterMode: 'nucleosynthesis',
    mechanic: 'fusion_window',
    accent: '#ffb45a',
    coreColor: '#ffe090',
    particleColors: ['#ff9c2f', '#ffd05b', '#fff0ba'],
    clickUpgradeName: 'Fusion Pulse',
    autoUpgradeName: 'Helium Forge',
    quote:
      'The furnace cools just enough for the first simple nuclei to hold. A narrow window decides the chemical future.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 5,
    name: 'Recombination',
    resource: 'Atoms',
    time: '215 Kyr',
    cosmicTimeSec: 6.8e12,
    realPlayTargetSec: 540,
    threshold: 1.285e11,
  clusterMode: 'recombination',
    mechanic: 'recombination',
    accent: '#63b7ff',
    coreColor: '#a8dcff',
    particleColors: ['#2f7bc1', '#67c0ff', '#d9f2ff'],
    clickUpgradeName: 'Electron Capture',
    autoUpgradeName: 'Photon Release',
    quote:
      'The fog thins. Electrons find their homes, and light finally moves freely through a transparent cosmos.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 6,
    name: 'Cosmic Dark Age',
    resource: 'Hydrogen',
    time: '100 Myr',
    cosmicTimeSec: 3.15e15,
    realPlayTargetSec: 1_800,
    threshold: 6e14,
  clusterMode: 'darkAge',
    mechanic: 'dark_age',
    accent: '#4e6188',
    coreColor: '#7d90b5',
    particleColors: ['#182237', '#3d4f73', '#92a4c8'],
    clickUpgradeName: 'Cold Drift',
    autoUpgradeName: 'Silent Accretion',
    quote:
      'No stars yet, no sunrise anywhere. Only neutral hydrogen drifting through a darkness that seems endless.',
    quoteAttr: 'Original cosmic prose',
    silenceBeforeMs: 5000,
  },
  {
    id: 7,
    name: 'First Stars',
    resource: 'Stars',
    time: '200 Myr',
    cosmicTimeSec: 6.3e15,
    realPlayTargetSec: 3_600,
    threshold: 2e16,
  clusterMode: 'firstStars',
    mechanic: 'first_stars',
    accent: '#eef3ff',
    coreColor: '#fffef8',
    particleColors: ['#d6ddff', '#fffef2', '#ffd9a5'],
    clickUpgradeName: 'Protostar Spark',
    autoUpgradeName: 'Population Igniter',
    quote:
      'The first stars arrive in blinding blue-white bursts. They live fast, die young, and rewrite the dark.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 8,
    name: 'Reionization',
    resource: 'Photons',
    time: '500 Myr',
    cosmicTimeSec: 1.6e16,
    realPlayTargetSec: 5_400,
    threshold: 2e17,
  clusterMode: 'reionization',
    mechanic: 'reionization',
    accent: '#9bd9ff',
    coreColor: '#dff5ff',
    particleColors: ['#4aa7de', '#8ed8ff', '#ecfbff'],
    clickUpgradeName: 'Ionizing Front',
    autoUpgradeName: 'Luminous Sweep',
    quote:
      'Starlight pushes back the neutral haze. The universe becomes legible one ionized frontier at a time.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 9,
    name: 'Galaxy Formation',
    resource: 'Galaxies',
    time: '1 Gyr',
    cosmicTimeSec: 3.15e16,
    realPlayTargetSec: 7_200,
    threshold: 1e18,
    clusterMode: 'galaxy',
    mechanic: 'galaxy_weaving',
    accent: '#6d8fff',
    coreColor: '#aab8ff',
    particleColors: ['#3548b6', '#6d8fff', '#d9ddff'],
    clickUpgradeName: 'Quasar Beam',
    autoUpgradeName: 'Web Spinner',
    quote:
      'Gravity gathers light into structure. Filaments, knots, and spirals reveal the hidden architecture of space.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 10,
    name: 'Solar System',
    resource: 'Worlds',
    time: '9.2 Gyr',
    cosmicTimeSec: 2.9e17,
    realPlayTargetSec: 10_800,
    threshold: 8e19,
    clusterMode: 'planetary',
    mechanic: 'planet_formation',
    accent: '#f7c86e',
    coreColor: '#ffe3a8',
    particleColors: ['#b77a35', '#f7c86e', '#fff0d1'],
    clickUpgradeName: 'Planetesimal Pull',
    autoUpgradeName: 'Accretion Disk',
    quote:
      'Around an ordinary star, dust keeps its appointments. Stone, metal, and ice negotiate the shapes of worlds.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 11,
    name: 'Life on Earth',
    resource: 'Memory',
    time: '13.8 Gyr',
    cosmicTimeSec: 4.35e17,
    realPlayTargetSec: 14_400,
    threshold: 2e20,
    clusterMode: 'lifeSurface',
    mechanic: 'life_evolution',
    accent: '#68d8a4',
    coreColor: '#a9f0d0',
    particleColors: ['#245f45', '#68d8a4', '#d7ffec'],
    clickUpgradeName: 'Living Spark',
    autoUpgradeName: 'Evolutionary Pressure',
    quote:
      'On one small rock, chemistry learns to remember itself. Almost everything you call history waits inside the final flicker.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 12,
    name: 'Death of Star',
    resource: 'Embers',
    time: '+5 Gyr',
    cosmicTimeSec: 5.83e17,
    realPlayTargetSec: 21_600,
    threshold: 6e20,
    clusterMode: 'redGiant',
    mechanic: 'red_giant',
    accent: '#ff633f',
    coreColor: '#ff9e71',
    particleColors: ['#ad2d1f', '#ff633f', '#ffd0ac'],
    clickUpgradeName: 'Last Light',
    autoUpgradeName: 'Red Giant Wind',
    quote:
      'The star swells without ceremony. What it consumes is precious only to those who once lived there.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 13,
    name: 'Stelliferous End',
    resource: 'Remnants',
    time: '1e14 yr',
    cosmicTimeSec: 3.15e21,
    realPlayTargetSec: 36_000,
    threshold: 2e21,
  clusterMode: 'remnant',
    mechanic: 'remnant_cooling',
    accent: '#8a90a8',
    coreColor: '#bec3d8',
    particleColors: ['#2a3044', '#7e88a5', '#d9deef'],
    clickUpgradeName: 'White Dwarf Cooler',
    autoUpgradeName: 'Iron Star Compression',
    quote:
      'The era of ordinary starlight ends. The universe keeps going, but the age of lamps is over.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 14,
    name: 'Degenerate Era',
    resource: 'Decays',
    time: '7e26 yr',
    cosmicTimeSec: 2.29e34,
    realPlayTargetSec: 54_000,
    threshold: 8e22,
  clusterMode: 'degenerate',
    mechanic: 'proton_decay',
    accent: '#8e69c9',
    coreColor: '#bf9af0',
    particleColors: ['#26133b', '#7c54b9', '#d8befd'],
    clickUpgradeName: 'Decay Catalyst',
    autoUpgradeName: 'Quantum Tunneling Loop',
    quote:
      'Even the most stubborn matter has an ending. Given enough time, solidity becomes a rumor.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 15,
    name: 'Black Hole Era',
    resource: 'Hawking Quanta',
    time: '1e28 yr',
    cosmicTimeSec: 3.89e35,
    realPlayTargetSec: 86_400,
    threshold: 3e23,
    clusterMode: 'blackHole',
    mechanic: 'hawking_radiation',
    accent: '#5b4671',
    coreColor: '#857299',
    particleColors: ['#12091b', '#352446', '#7d6a91'],
    clickUpgradeName: 'Hawking Radiator',
    autoUpgradeName: 'Event Horizon Drain',
    quote:
      'Black holes inherit the silence. They rule an empty kingdom with a patience measured in impossible years.',
    quoteAttr: 'Original cosmic prose',
  },
  {
    id: 16,
    name: 'The End',
    resource: 'Outcomes',
    time: '2e30 yr',
    cosmicTimeSec: 5.01e37,
    realPlayTargetSec: 117_450,
    threshold: 1.2e24,
    clusterMode: 'heatDeath',
    mechanic: 'ending_choice',
    accent: '#70758a',
    coreColor: '#b0b5c7',
    particleColors: ['#050608', '#3c4050', '#8b92a8'],
    clickUpgradeName: 'Vacuum Flicker',
    autoUpgradeName: 'Final Divergence',
    quote:
      'Everything approaches equilibrium. And still, at the far edge of silence, one last possibility trembles.',
    quoteAttr: 'Original cosmic prose',
    silenceBeforeMs: 7000,
  },
];

function getTimelinePos(cosmicTimeSec: number, minLog: number, maxLog: number): number {
  const logValue = Math.log10(cosmicTimeSec);
  if (maxLog === minLog) {
    return 0;
  }
  return ((logValue - minLog) / (maxLog - minLog)) * 100;
}

const cosmicLogs = STAGE_DEFINITIONS.map((stage) => Math.log10(stage.cosmicTimeSec));
const minLog = Math.min(...cosmicLogs);
const maxLog = Math.max(...cosmicLogs);

const ZOOM_DIRECTION_BY_STAGE: Record<number, Stage['zoomDirection']> = {
  1: 'none',
  2: 'out',
  3: 'out',
  4: 'out',
  5: 'out',
  6: 'out',
  7: 'out',
  8: 'out',
  9: 'out',
  10: 'in',
  11: 'in',
  12: 'out',
  13: 'out',
  14: 'out',
  15: 'in',
  16: 'out',
};

const BACKGROUNDS_BY_STAGE: Record<number, StageBackground> = {
  1: {
    gradientTop: '#2b0803',
    gradientBottom: '#050102',
    nebulaIntensity: 0.42,
    starDensity: 0,
    starColor: '#fff3dd',
    distantElementColor: '#ff6b3d',
    distantElements: 'expansion_burst',
  },
  2: {
    gradientTop: '#2d1004',
    gradientBottom: '#050102',
    nebulaIntensity: 0.36,
    starDensity: 0.08,
    starColor: '#ffe2b5',
    distantElementColor: '#ff8a47',
    distantElements: 'pair_streaks',
  },
  3: {
    gradientTop: '#33100a',
    gradientBottom: '#060103',
    nebulaIntensity: 0.48,
    starDensity: 0.05,
    starColor: '#fff2c9',
    distantElementColor: '#ff6a45',
    distantElements: 'plasma_swirl',
  },
  4: {
    gradientTop: '#3b2106',
    gradientBottom: '#060302',
    nebulaIntensity: 0.34,
    starDensity: 0.18,
    starColor: '#fff0ba',
    distantElementColor: '#ffb45a',
    distantElements: 'void',
  },
  5: {
    gradientTop: '#08203a',
    gradientBottom: '#02070d',
    nebulaIntensity: 0.28,
    starDensity: 0.42,
    starColor: '#d9f2ff',
    distantElementColor: '#63b7ff',
    distantElements: 'clearing_fog',
  },
  6: {
    gradientTop: '#060912',
    gradientBottom: '#010207',
    nebulaIntensity: 0.08,
    starDensity: 0.22,
    starColor: '#92a4c8',
    distantElementColor: '#4e6188',
    distantElements: 'void',
  },
  7: {
    gradientTop: '#0d1426',
    gradientBottom: '#02030a',
    nebulaIntensity: 0.16,
    starDensity: 0.76,
    starColor: '#eef3ff',
    distantElementColor: '#eef3ff',
    distantElements: 'bright_pinpoints',
  },
  8: {
    gradientTop: '#08263b',
    gradientBottom: '#020713',
    nebulaIntensity: 0.24,
    starDensity: 0.68,
    starColor: '#ecfbff',
    distantElementColor: '#9bd9ff',
    distantElements: 'ionization_bubbles',
  },
  9: {
    gradientTop: '#0a1233',
    gradientBottom: '#02030d',
    nebulaIntensity: 0.3,
    starDensity: 0.86,
    starColor: '#d9ddff',
    distantElementColor: '#6d8fff',
    distantElements: 'galaxy_field',
  },
  10: {
    gradientTop: '#14110a',
    gradientBottom: '#030304',
    nebulaIntensity: 0.18,
    starDensity: 0.72,
    starColor: '#fff0d1',
    distantElementColor: '#f7c86e',
    distantElements: 'nearby_stars',
  },
  11: {
    gradientTop: '#071a14',
    gradientBottom: '#010403',
    nebulaIntensity: 0.16,
    starDensity: 0.64,
    starColor: '#d7ffec',
    distantElementColor: '#68d8a4',
    distantElements: 'earth_orbit',
  },
  12: {
    gradientTop: '#2a0804',
    gradientBottom: '#050101',
    nebulaIntensity: 0.36,
    starDensity: 0.48,
    starColor: '#ffd0ac',
    distantElementColor: '#ff633f',
    distantElements: 'red_shroud',
  },
  13: {
    gradientTop: '#0d1018',
    gradientBottom: '#020207',
    nebulaIntensity: 0.1,
    starDensity: 0.34,
    starColor: '#d9deef',
    distantElementColor: '#8a90a8',
    distantElements: 'fading_stars',
  },
  14: {
    gradientTop: '#13091f',
    gradientBottom: '#020104',
    nebulaIntensity: 0.08,
    starDensity: 0.24,
    starColor: '#d8befd',
    distantElementColor: '#8e69c9',
    distantElements: 'dim_specks',
  },
  15: {
    gradientTop: '#09040f',
    gradientBottom: '#000000',
    nebulaIntensity: 0.14,
    starDensity: 0.38,
    starColor: '#cbb9dd',
    distantElementColor: '#857299',
    distantElements: 'lensed_field',
  },
  16: {
    gradientTop: '#06070a',
    gradientBottom: '#000000',
    nebulaIntensity: 0.04,
    starDensity: 0.16,
    starColor: '#8b92a8',
    distantElementColor: '#70758a',
    distantElements: 'redshifted_void',
  },
};

export const STAGES: Stage[] = STAGE_DEFINITIONS.map((stage, index, stages) => {
  const previousCosmicTime = index === 0 ? 0 : stages[index - 1].cosmicTimeSec;

  return {
    ...stage,
    background: BACKGROUNDS_BY_STAGE[stage.id],
    cosmicTimeSpanSec: stage.cosmicTimeSec - previousCosmicTime,
    timelinePos: getTimelinePos(stage.cosmicTimeSec, minLog, maxLog),
    zoomDirection: ZOOM_DIRECTION_BY_STAGE[stage.id],
  };
});

export const COSMIC_TIME_UNITS = {
  yearSeconds: COSMIC_YEAR_SECONDS,
} as const;
